/* ================================================================
   puzzles.js  —  Brain Blast! v2
   ================================================================
   15 CATEGORIES based on uploaded puzzle_categories.txt:
     1.  math        🔢  Story-based math & counting
     2.  logic       🧩  Odd one out, reasoning
     3.  pattern     🔁  Number & shape patterns
     4.  story       📖  Real-life situation problems
     5.  visual      👁️  Emoji-based recognition
     6.  memory      🧠  Recall & sequence memory
     7.  speed       ⚡  Quick-fire arithmetic
     8.  comparison  ⚖️  Bigger / smaller / heavier
     9.  sequence    📅  Order & next-in-series logic
    10.  word        📝  Vocabulary & language
    11.  animals     🐾  Fun animal facts & recognition
    12.  colors      🎨  Colour recognition & mixing
    13.  shapes      🔷  Geometry basics
    14.  trick       🎩  Trick & lateral thinking questions
    15.  emotional   ❤️  Behaviour & empathy

   DIFFICULTY auto-unlocked by score (see game.js CONFIG):
     easy   →  0 – 14 correct
     medium → 15 – 29 correct
     hard   → 30+ correct

   HOW TO ADD A QUESTION:
     { q: "Question text?", o: ["A","B","C","D"], a: "A" }
   Every 'a' MUST exactly match one entry in 'o'.
================================================================ */

const PUZZLES = {

  /* ── 1. MATH 🔢 ─────────────────────────────────────────────
     Style: story-based, visual counting, monkey-themed          */
  math: {
    easy: [
      { q:"🍎 You have 5 apples and give 2 away. How many left?",      o:["2","3","4","5"],        a:"3" },
      { q:"🐵 Monkey has 3 bananas, gets 2 more. Total bananas?",      o:["4","5","6","7"],        a:"5" },
      { q:"🍕 There are 4 slices. You eat 1. How many remain?",        o:["2","3","4","5"],        a:"3" },
      { q:"⭐ Count the stars: ⭐⭐⭐⭐⭐",                             o:["3","4","5","6"],        a:"5" },
      { q:"🐣 2 chicks hatch, then 3 more. Total chicks?",             o:["4","5","6","7"],        a:"5" },
      { q:"🎈 You have 6 balloons. 2 pop. How many left?",             o:["3","4","5","6"],        a:"4" },
      { q:"🍬 3 sweets + 3 sweets = ?",                                o:["4","5","6","7"],        a:"6" },
      { q:"🌟 Count: 🌟🌟🌟",                                          o:["2","3","4","5"],        a:"3" },
      { q:"🐟 4 fish in a pond, 2 swim away. Fish left?",              o:["1","2","3","4"],        a:"2" },
      { q:"🚂 Train has 2 + 2 carriages. Total carriages?",            o:["2","3","4","5"],        a:"4" },
      { q:"🌈 7 colours in a rainbow. Remove 2. Left?",                o:["4","5","6","7"],        a:"5" },
      { q:"🍩 You bake 4 donuts, eat 1. How many left?",               o:["2","3","4","5"],        a:"3" },
      { q:"🐝 3 bees + 4 bees = ?",                                    o:["5","6","7","8"],        a:"7" },
      { q:"🌻 Plant 5 seeds. 3 grow. How many didn't grow?",           o:["1","2","3","4"],        a:"2" },
      { q:"🎯 Score 3 points, then 4 more. Total score?",              o:["5","6","7","8"],        a:"7" },
    ],
    medium: [
      { q:"🍎 You have 12 apples. Give 5 to friends. How many left?",  o:["5","6","7","8"],        a:"7" },
      { q:"🐵 Monkey collects 8 bananas/day for 3 days. Total?",       o:["22","24","26","28"],    a:"24" },
      { q:"🍕 Pizza has 8 slices. 3 friends share equally. Each gets?",o:["2","3","4","5"],        a:"2" },
      { q:"🎈 25 balloons. 8 pop, then 5 more pop. Left?",             o:["10","11","12","13"],   a:"12" },
      { q:"🏀 Score 15 in first half, 13 in second. Total?",           o:["26","27","28","29"],   a:"28" },
      { q:"🚗 Car travels 6 km/hr. Distance in 4 hours?",              o:["20","22","24","26"],   a:"24" },
      { q:"🍫 Box has 24 chocolates. Shared among 4. Each gets?",      o:["4","5","6","7"],        a:"6" },
      { q:"⏰ Journey takes 45 min. Starts at 9:00. Ends at?",         o:["9:30","9:45","10:00","10:15"],a:"9:45" },
      { q:"📚 Read 15 pages/day. Pages in 6 days?",                    o:["80","85","90","95"],   a:"90" },
      { q:"🌴 Tree grows 3 cm/month. Growth in 9 months?",             o:["24","27","30","33"],   a:"27" },
      { q:"🎪 36 children in 4 equal groups. Each group size?",        o:["7","8","9","10"],       a:"9" },
      { q:"🍰 Cake cut into 12 slices. 7 eaten. Left?",                o:["4","5","6","7"],        a:"5" },
      { q:"⚽ Team plays 10 games, wins 6, draws 2. Losses?",          o:["1","2","3","4"],        a:"2" },
      { q:"🎟️ Tickets cost $9. Buy 7. Total cost?",                    o:["$60","$63","$66","$69"],a:"$63" },
      { q:"🦋 Garden has 5 flowers each with 4 butterflies. Total?",   o:["18","20","22","24"],   a:"20" },
    ],
    hard: [
      { q:"🍎 Orchard: 144 apples in 12 equal baskets. Per basket?",   o:["10","11","12","13"],  a:"12" },
      { q:"🐵 Monkey tribe eats 7 bananas/day. Bananas for 3 weeks?",  o:["141","147","153","159"],a:"147" },
      { q:"🚗 Car: 60 km/h. Train: 90 km/h. Train advantage in 2 hrs?",o:["55","60","65","70"],  a:"60" },
      { q:"📦 Box holds 24 items. Need 300 items. Boxes needed?",       o:["11","12","13","14"],  a:"13" },
      { q:"💰 Save $12/week for 8 weeks. Spend $38. Left?",            o:["56","58","60","62"],   a:"58" },
      { q:"🎪 Hall: 18 rows × 24 seats. Total seats?",                 o:["420","428","432","436"],a:"432" },
      { q:"🌊 Ship travels 240 km in 4 hours. Speed (km/h)?",          o:["55","60","65","70"],   a:"60" },
      { q:"🏃 Run 400 m in 80 s. Speed in m/s?",                       o:["4","5","6","7"],       a:"5" },
      { q:"📐 Rectangle: 18 cm × 12 cm. Area?",                       o:["200","210","216","220"],a:"216" },
      { q:"🔢 Average of 18, 24, 30, 36 = ?",                         o:["24","26","27","28"],   a:"27" },
      { q:"🎯 ⅓ of 360 = ?",                                           o:["100","110","120","130"],a:"120" },
      { q:"🌍 Earth radius ≈ 6371 km. Diameter ≈ ?",                   o:["12 700 km","12 742 km","12 800 km","13 000 km"],a:"12 742 km" },
      { q:"⏱️ 2.5 hours = how many minutes?",                          o:["120","140","150","160"],a:"150" },
      { q:"🍕 ¾ of 48 pizzas = ?",                                     o:["32","34","36","38"],   a:"36" },
      { q:"🚂 Train: 90 km/h for 2.5 hours. Distance?",               o:["200","210","220","225"],a:"225" },
    ],
  },

  /* ── 2. LOGIC 🧩 ─────────────────────────────────────────────
     Style: odd one out, which doesn't belong, reasoning          */
  logic: {
    easy: [
      { q:"🐶🐶🐱🐶 — which is different?",                           o:["🐶","🐱","Both","None"],a:"🐱" },
      { q:"Which does NOT belong: Apple, Banana, Car?",               o:["Apple","Banana","Car","All belong"],a:"Car" },
      { q:"Which is NOT a colour: Red, Happy, Blue?",                 o:["Red","Happy","Blue","All are"],a:"Happy" },
      { q:"Odd one out: Dog, Cat, Fish, Chair?",                      o:["Dog","Cat","Fish","Chair"],a:"Chair" },
      { q:"Which can you eat: Stone, Bread, Iron, Sand?",             o:["Stone","Bread","Iron","Sand"],a:"Bread" },
      { q:"Which is NOT a number: 1, 2, Three, 4?",                   o:["1","2","Three","4"],       a:"Three" },
      { q:"Which can fly: Fish, Dog, Bird, Cow?",                     o:["Fish","Dog","Bird","Cow"],  a:"Bird" },
      { q:"Odd one out: Circle, Square, Triangle, Monday?",           o:["Circle","Square","Triangle","Monday"],a:"Monday" },
      { q:"Which is NOT a fruit: Mango, Car, Apple, Grape?",          o:["Mango","Car","Apple","Grape"],a:"Car" },
      { q:"Which can swim: Cat, Horse, Fish, Eagle?",                 o:["Cat","Horse","Fish","Eagle"],a:"Fish" },
      { q:"Odd one out: Sun, Moon, Star, Chair?",                     o:["Sun","Moon","Star","Chair"],a:"Chair" },
      { q:"Which is NOT a vegetable: Carrot, Potato, Rose, Pea?",     o:["Carrot","Potato","Rose","Pea"],a:"Rose" },
      { q:"Which is NOT alive: Tree, Stone, Dog, Flower?",            o:["Tree","Stone","Dog","Flower"],a:"Stone" },
      { q:"Which is NOT round: Ball, Apple, Brick, Orange?",          o:["Ball","Apple","Brick","Orange"],a:"Brick" },
      { q:"Odd one out: January, February, Monday, March?",           o:["January","February","Monday","March"],a:"Monday" },
    ],
    medium: [
      { q:"Odd one out: Hammer, Saw, Nail, Paintbrush?",              o:["Hammer","Saw","Nail","Paintbrush"],a:"Nail" },
      { q:"Which doesn't belong: Piano, Guitar, Drums, Painting?",    o:["Piano","Guitar","Drums","Painting"],a:"Painting" },
      { q:"Which is NOT a planet: Mars, Venus, Sun, Jupiter?",        o:["Mars","Venus","Sun","Jupiter"],a:"Sun" },
      { q:"If all roses are flowers, are all flowers roses?",         o:["Yes","No","Maybe","Sometimes"],a:"No" },
      { q:"Odd one out: Eagle, Penguin, Parrot, Sparrow?",            o:["Eagle","Penguin","Parrot","Sparrow"],a:"Penguin" },
      { q:"Which is NOT a mammal: Whale, Shark, Dog, Elephant?",      o:["Whale","Shark","Dog","Elephant"],a:"Shark" },
      { q:"Odd one out: Add, Subtract, Multiply, Run?",               o:["Add","Subtract","Multiply","Run"],a:"Run" },
      { q:"Which is NOT a primary colour: Red, Blue, Green, Yellow?", o:["Red","Blue","Green","Yellow"],a:"Green" },
      { q:"Which group is correct: 2+2=4, 3×3=9, 5-2=4?",            o:["2+2=4","3×3=9","5-2=4","None"],a:"5-2=4" },
      { q:"All squares are rectangles. Is every rectangle a square?", o:["Yes","No","Sometimes","Always"],a:"No" },
      { q:"Which is NOT liquid at room temp: Water, Milk, Ice, Oil?", o:["Water","Milk","Ice","Oil"],a:"Ice" },
      { q:"Odd one out: Copper, Iron, Wood, Gold?",                   o:["Copper","Iron","Wood","Gold"],a:"Wood" },
      { q:"Which does NOT produce sound: Bell, Book, Drum, Guitar?",  o:["Bell","Book","Drum","Guitar"],a:"Book" },
      { q:"Odd one out: Author, Painter, Sculptor, Audience?",        o:["Author","Painter","Sculptor","Audience"],a:"Audience" },
      { q:"Which does NOT need sunlight to grow: Mushroom, Rose, Grass, Wheat?",o:["Mushroom","Rose","Grass","Wheat"],a:"Mushroom" },
    ],
    hard: [
      { q:"All Bloops are Razzies. All Razzies are Lazzies. Are all Bloops Lazzies?", o:["Yes","No","Maybe","Cannot say"],a:"Yes" },
      { q:"No fish are mammals. Dolphins are fish. Are dolphins mammals?",            o:["Yes","No","Maybe","Sometimes"],a:"No" },
      { q:"Odd one out (by number of sides): Triangle, Square, Pentagon, Circle?",    o:["Triangle","Square","Pentagon","Circle"],a:"Circle" },
      { q:"🔢 If today is Monday, what day is it 100 days later?",                    o:["Monday","Tuesday","Wednesday","Thursday"],a:"Wednesday" },
      { q:"Which word is the odd one out: Regal, Legal, Frugal, Royal?",              o:["Regal","Legal","Frugal","Royal"],a:"Royal" },
      { q:"5 machines make 5 toys in 5 min. How long for 1 machine to make 1 toy?",  o:["1 min","5 min","10 min","25 min"],a:"5 min" },
      { q:"Odd one out by pattern: 2,4,8,16 vs 1,3,5,7 — which set has an odd number?",o:["First set","Second set","Both","Neither"],a:"Second set" },
      { q:"If ROAD is coded as URDG, how is SWAN coded?",                             o:["VZDQ","VZEQ","VXEQ","VZEP"],a:"VZDQ" },
      { q:"Odd one out: Area, Volume, Weight, Colour?",                               o:["Area","Volume","Weight","Colour"],a:"Colour" },
      { q:"All metals conduct electricity. Copper is a metal. Does copper conduct?",  o:["Yes","No","Maybe","Depends"],a:"Yes" },
      { q:"Odd one out: Noun, Verb, Adjective, Sentence?",                            o:["Noun","Verb","Adjective","Sentence"],a:"Sentence" },
      { q:"Which is NOT a logical operator: AND, OR, NOT, MAYBE?",                   o:["AND","OR","NOT","MAYBE"],a:"MAYBE" },
      { q:"A is taller than B. B is taller than C. Who is shortest?",                o:["A","B","C","Cannot say"],a:"C" },
      { q:"Odd one out: Simile, Metaphor, Hyperbole, Equation?",                     o:["Simile","Metaphor","Hyperbole","Equation"],a:"Equation" },
      { q:"Every square is a rhombus. Is every rhombus a square?",                   o:["Yes","No","Sometimes","Always"],a:"No" },
    ],
  },

  /* ── 3. PATTERN 🔁 ───────────────────────────────────────────
     Style: number sequences, shape/emoji patterns                */
  pattern: {
    easy: [
      { q:"🔢 Next: 1, 3, 5, ?",                                      o:["6","7","8","9"],        a:"7" },
      { q:"🔴🔵🔴🔵 — what comes next?",                              o:["🔴","🔵","🟡","🟢"],    a:"🔴" },
      { q:"🔢 Next: 2, 4, 6, 8, ?",                                   o:["9","10","11","12"],     a:"10" },
      { q:"🔺🔵🔺🔵🔺 — what comes next?",                           o:["🔺","🔵","🟡","🟢"],    a:"🔵" },
      { q:"🔢 Next: 5, 10, 15, 20, ?",                                o:["22","23","25","30"],    a:"25" },
      { q:"🐶🐱🐶🐱 — what comes next?",                              o:["🐶","🐱","🐰","🐸"],    a:"🐶" },
      { q:"🔢 Next: 10, 9, 8, 7, ?",                                  o:["4","5","6","7"],        a:"6" },
      { q:"⭐🌙⭐🌙 — what comes next?",                              o:["⭐","🌙","☀️","🌟"],    a:"⭐" },
      { q:"🔢 Next: 1, 2, 3, 4, ?",                                   o:["4","5","6","7"],        a:"5" },
      { q:"🍎🍊🍎🍊 — what comes next?",                              o:["🍎","🍊","🍋","🍇"],    a:"🍎" },
      { q:"🔢 Next: 3, 6, 9, 12, ?",                                  o:["13","14","15","16"],    a:"15" },
      { q:"🟥🟦🟥🟦 — what comes next?",                              o:["🟥","🟦","🟩","🟨"],    a:"🟥" },
      { q:"🔢 Next: 0, 2, 4, 6, ?",                                   o:["7","8","9","10"],       a:"8" },
      { q:"🌸🌻🌸🌻 — what comes next?",                              o:["🌸","🌻","🌹","🌷"],    a:"🌸" },
      { q:"🔢 Next: 100, 90, 80, 70, ?",                              o:["55","60","65","70"],    a:"60" },
    ],
    medium: [
      { q:"🔢 Next: 1, 4, 9, 16, ?",                                  o:["20","24","25","30"],    a:"25" },
      { q:"🔢 Next: 2, 6, 18, 54, ?",                                 o:["108","162","216","270"],a:"162" },
      { q:"🔢 Next: 1, 1, 2, 3, 5, 8, ?",                            o:["11","12","13","14"],    a:"13" },
      { q:"🔢 Next: 3, 6, 12, 24, ?",                                 o:["36","42","48","60"],    a:"48" },
      { q:"🔢 Next: 81, 64, 49, 36, ?",                               o:["25","24","28","30"],    a:"25" },
      { q:"🔺🔺🔵🔺🔺🔵 — what comes next?",                        o:["🔺","🔵","🟡","🟢"],    a:"🔺" },
      { q:"🔢 Next: 5, 8, 11, 14, ?",                                 o:["16","17","18","19"],    a:"17" },
      { q:"🔢 Next: 100, 50, 25, ?",                                   o:["10","12","12.5","15"],  a:"12.5" },
      { q:"🔢 Next: 2, 3, 5, 8, 12, ?",                               o:["15","16","17","18"],    a:"17" },
      { q:"🔢 Next: 729, 243, 81, 27, ?",                             o:["6","7","8","9"],        a:"9" },
      { q:"🌑🌒🌓🌔 — what comes next?",                             o:["🌕","🌑","🌒","🌙"],    a:"🌕" },
      { q:"🔢 Next: 1, 2, 4, 7, 11, ?",                               o:["14","15","16","17"],    a:"16" },
      { q:"🔢 Next: 6, 11, 16, 21, ?",                                o:["24","25","26","27"],    a:"26" },
      { q:"ABAB pattern: 🐘🦒🐘🦒 — next?",                          o:["🐘","🦒","🐆","🦓"],    a:"🐘" },
      { q:"🔢 Next: 4, 8, 16, 32, ?",                                 o:["48","56","64","72"],    a:"64" },
    ],
    hard: [
      { q:"🔢 Next: 1, 8, 27, 64, ?",                                 o:["100","115","125","135"],a:"125" },
      { q:"🔢 Next: 0, 1, 1, 2, 3, 5, 8, 13, ?",                     o:["19","20","21","22"],    a:"21" },
      { q:"🔢 Next: 10, 9, 7, 4, ?",                                  o:["0","1","2","3"],        a:"0" },
      { q:"🔢 Next: 2, 5, 11, 23, ?",                                 o:["44","46","47","48"],    a:"47" },
      { q:"🔢 Next: 1, 4, 10, 20, 35, ?",                             o:["52","54","56","58"],    a:"56" },
      { q:"🔢 Next: 3, 7, 13, 21, 31, ?",                             o:["40","42","43","44"],    a:"43" },
      { q:"🔢 Next: 1, 3, 6, 10, 15, ?",                              o:["19","20","21","22"],    a:"21" },
      { q:"🔢 Pattern: 2, 3, 5, 7, 11, 13, ? (primes)",              o:["15","17","19","21"],    a:"17" },
      { q:"🔢 Next: 4, 7, 12, 19, 28, ?",                             o:["37","38","39","40"],    a:"39" },
      { q:"🔢 Next: 256, 64, 16, 4, ?",                               o:["1","2","3","4"],        a:"1" },
      { q:"🔢 Next: 1, 2, 6, 24, 120, ?",                             o:["480","600","720","840"],a:"720" },
      { q:"🔢 Rule is ×3 −1. Next after 26?",                         o:["75","77","79","81"],    a:"77" },
      { q:"🔢 Next: 1, 5, 14, 30, 55, ?",                             o:["86","90","91","95"],    a:"91" },
      { q:"🔢 Next: 2, 8, 18, 32, 50, ?",                             o:["68","70","72","74"],    a:"72" },
      { q:"🔢 Next: 1, 2, 4, 8, 16, 32, ?",                          o:["48","56","64","72"],    a:"64" },
    ],
  },

  /* ── 4. STORY 📖 ─────────────────────────────────────────────
     Style: real-life situation word problems                     */
  story: {
    easy: [
      { q:"🚗 Ravi has 3 cars. Buys 2 more. Total cars?",             o:["4","5","6","7"],        a:"5" },
      { q:"🍬 You had 6 candies. Ate 2. How many left?",              o:["3","4","5","6"],        a:"4" },
      { q:"🐔 Farm has 5 hens. 2 fly away. Hens left?",               o:["2","3","4","5"],        a:"3" },
      { q:"📚 Shelf has 8 books. Borrow 3. Books on shelf?",          o:["4","5","6","7"],        a:"5" },
      { q:"🌼 Plant 4 seeds on Monday, 3 on Tuesday. Total seeds?",   o:["5","6","7","8"],        a:"7" },
      { q:"🎒 Bag has 5 pencils. Lose 1. Pencils left?",              o:["3","4","5","6"],        a:"4" },
      { q:"🏠 House has 4 rooms. Add 1 more. Total rooms?",           o:["4","5","6","7"],        a:"5" },
      { q:"🐮 Farmer has 6 cows. Sells 2. Cows left?",                o:["3","4","5","6"],        a:"4" },
      { q:"🍦 3 friends each get 2 ice creams. Total ice creams?",    o:["4","5","6","7"],        a:"6" },
      { q:"⚽ Match: Team A scores 3, Team B scores 1. Winner's score?",o:["1","2","3","4"],       a:"3" },
      { q:"🎁 Wrap 2 gifts with 1 m ribbon each. Ribbon used?",       o:["1 m","2 m","3 m","4 m"],a:"2 m" },
      { q:"🍊 Bag of 10 oranges. Give 4 away. Left?",                 o:["5","6","7","8"],        a:"6" },
      { q:"🐇 3 rabbits, each with 2 ears. Total ears?",              o:["4","5","6","7"],        a:"6" },
      { q:"🌧️ Rained 3 days this week. Sunny days?",                  o:["3","4","5","6"],        a:"4" },
      { q:"🎂 Birthday cake cut into 8 slices. 5 eaten. Left?",       o:["2","3","4","5"],        a:"3" },
    ],
    medium: [
      { q:"🛒 Apples $3 each. Buy 7. Total cost?",                    o:["$19","$20","$21","$22"],a:"$21" },
      { q:"⏰ Movie is 90 min. Starts 3 pm. What time does it end?",  o:["4:00 pm","4:30 pm","5:00 pm","5:30 pm"],a:"4:30 pm" },
      { q:"🚌 Bus has 24 seats. 17 are taken. Empty seats?",          o:["5","6","7","8"],        a:"7" },
      { q:"🍰 Recipe: 3 eggs per cake. Make 5 cakes. Eggs needed?",   o:["13","14","15","16"],    a:"15" },
      { q:"🐄 Each cow gives 5 L milk. 8 cows give total?",           o:["35","38","40","42"],    a:"40" },
      { q:"🏃 Run 3 km/day for 2 weeks. Total km?",                   o:["38","40","42","44"],    a:"42" },
      { q:"📦 Box holds 15 books. Need 75 books. Boxes needed?",      o:["4","5","6","7"],        a:"5" },
      { q:"🎟️ Entry fee $6. 9 children enter. Total collected?",      o:["$48","$52","$54","$56"],a:"$54" },
      { q:"⚽ League: 8 teams. Each plays every other once. Total games?",o:["24","26","28","30"],a:"28" },
      { q:"🌿 Plant grows 4 cm/week. Height after 7 weeks?",          o:["24","26","28","30"],    a:"28" },
      { q:"🍕 Pizza $14. Split 3 ways equally. Each pays?",           o:["$4","$5","$6","$7"],    a:"$5" },
      { q:"🎨 Need 2 tins of paint per wall. 6 walls. Tins needed?",  o:["10","11","12","13"],    a:"12" },
      { q:"✈️ Flight 6 hrs. Departs 8 am. Arrival time?",             o:["1 pm","2 pm","3 pm","4 pm"],a:"2 pm" },
      { q:"🏊 Pool: 25 m/lap. Swim 1 km. How many laps?",             o:["35","38","40","42"],    a:"40" },
      { q:"🚶 Walk 4 km/hr. 2.5 hrs. Distance covered?",              o:["8","9","10","11"],      a:"10" },
    ],
    hard: [
      { q:"🏪 Store: 345 Mon + 278 Tue sales. Total?",                o:["621","623","625","627"],a:"623" },
      { q:"💧 Tank 500 L. Drains 35 L/day. Days to empty?",           o:["13","14","15","16"],    a:"14" },
      { q:"🎡 3 rows of 12 + 2 rows of 8 seats. Total seats?",        o:["50","52","54","56"],    a:"52" },
      { q:"🧱 Wall needs 850 bricks. Laid 340. Remaining?",           o:["500","505","510","515"],a:"510" },
      { q:"💰 Earn $240/week. Spend $175. Save for 6 weeks?",         o:["$370","$385","$390","$395"],a:"$390" },
      { q:"🌍 Earth radius ≈ 6371 km. Circumference ≈ ? (use π≈3.14)",o:["39 950 km","40 010 km","40 030 km","40 074 km"],a:"40 030 km" },
      { q:"🏋️ Weights: 12.5 kg + 8.75 kg + 6.25 kg. Total?",        o:["26.5","27","27.5","28"],a:"27.5" },
      { q:"📐 Triangle area = ½ × 14 × 9. Area = ?",                  o:["56","60","63","66"],    a:"63" },
      { q:"🚢 Ship: 240 km in 4 hrs. How far in 7 hrs?",              o:["400","410","420","430"],a:"420" },
      { q:"⏱️ 3 workers build a wall in 12 days. 6 workers do it in?",o:["4 days","5 days","6 days","8 days"],a:"6 days" },
      { q:"🔢 Average of 42, 56, 38, 64, 50 = ?",                    o:["48","50","52","54"],    a:"50" },
      { q:"🌱 Tree: 3 m. Grows 45 cm/yr. Height after 4 years?",      o:["4.6 m","4.7 m","4.8 m","4.9 m"],a:"4.8 m" },
      { q:"🎯 Lose 10% of 80 points, gain 25%. Final score?",         o:["85","88","90","92"],    a:"90" },
      { q:"🚂 Train 90 km/h for 2 hr 40 min. Distance?",              o:["230","240","245","250"],a:"240" },
      { q:"💡 Bulb: 60W. Cost $0.10/kWh. Cost for 5 hrs?",           o:["$0.02","$0.03","$0.05","$0.06"],a:"$0.03" },
    ],
  },

  /* ── 5. VISUAL 👁️ ────────────────────────────────────────────
     Style: emoji-based recognition, colour/object patterns       */
  visual: {
    easy: [
      { q:"🔴🟢🔴🟢 — what comes next?",                             o:["🔴","🟢","🔵","🟡"],    a:"🔴" },
      { q:"Which animal can fly? 🐟 🐕 🦅 🐄",                       o:["🐟","🐕","🦅","🐄"],    a:"🦅" },
      { q:"🍎🍊🍎🍊 — what comes next?",                              o:["🍎","🍊","🍋","🍇"],    a:"🍎" },
      { q:"Which lives in water? 🐱 🐟 🐶 🐔",                       o:["🐱","🐟","🐶","🐔"],    a:"🐟" },
      { q:"🌞🌧️🌞🌧️ — what comes next?",                            o:["🌞","🌧️","❄️","🌈"],   a:"🌞" },
      { q:"Which is a vehicle? 🍕 🚗 🌸 📚",                         o:["🍕","🚗","🌸","📚"],    a:"🚗" },
      { q:"Count: 🐵🐵🐵🐵 — how many monkeys?",                     o:["3","4","5","6"],        a:"4" },
      { q:"Which is sweet? 🍭 🧅 🥦 🧄",                             o:["🍭","🧅","🥦","🧄"],    a:"🍭" },
      { q:"🟦🟨🟦🟨 — what comes next?",                              o:["🟦","🟨","🟥","🟩"],    a:"🟦" },
      { q:"Which gives us milk? 🐟 🐄 🦅 🐕",                        o:["🐟","🐄","🦅","🐕"],    a:"🐄" },
      { q:"Which is a tool? 🍕 🔨 🌸 🐟",                            o:["🍕","🔨","🌸","🐟"],    a:"🔨" },
      { q:"🌙⭐🌙⭐ — what comes next?",                              o:["🌙","⭐","☀️","🌟"],    a:"🌙" },
      { q:"Which is hot? ❄️ 🔥 💧 🌊",                               o:["❄️","🔥","💧","🌊"],   a:"🔥" },
      { q:"Which has wings? 🐍 🦋 🐢 🐟",                            o:["🐍","🦋","🐢","🐟"],    a:"🦋" },
      { q:"Which is a fruit? 🥕 🥔 🍓 🧅",                           o:["🥕","🥔","🍓","🧅"],    a:"🍓" },
    ],
    medium: [
      { q:"🐘🦒🐘🦒🐘 — what comes next?",                           o:["🐘","🦒","🦓","🐆"],    a:"🦒" },
      { q:"Which symbol means multiply? + − × ÷",                     o:["+","−","×","÷"],        a:"×" },
      { q:"🔴🟡🔵🔴🟡 — what comes next?",                           o:["🔴","🟡","🔵","🟢"],    a:"🔵" },
      { q:"Which flag belongs to Japan? 🇺🇸 🇯🇵 🇬🇧 🇨🇳",          o:["🇺🇸","🇯🇵","🇬🇧","🇨🇳"],a:"🇯🇵" },
      { q:"Which emoji shows anger? 😊 😢 😡 😴",                     o:["😊","😢","😡","😴"],    a:"😡" },
      { q:"🍕🍔🍕🍔🍕 — what comes next?",                            o:["🍕","🍔","🌮","🍟"],    a:"🍔" },
      { q:"Which planet is shown? 🌍 — Earth, Mars, Venus, Jupiter?", o:["Earth","Mars","Venus","Jupiter"],a:"Earth" },
      { q:"Which shows 'greater than'? < > = ≠",                      o:["<",">","=","≠"],        a:">" },
      { q:"🌱🌿🌳🌱🌿 — what comes next?",                           o:["🌱","🌿","🌳","🌲"],    a:"🌳" },
      { q:"Which emoji shows sadness? 😄 🥳 😭 😎",                   o:["😄","🥳","😭","😎"],    a:"😭" },
      { q:"Which is a musical instrument? 🎸 🎃 🎯 🏀",               o:["🎸","🎃","🎯","🏀"],    a:"🎸" },
      { q:"🏖️🏔️🏖️🏔️ — what comes next?",                          o:["🏖️","🏔️","🌲","🏕️"],a:"🏖️" },
      { q:"Which shows balance? ⚖️ 🔨 🔑 🎯",                        o:["⚖️","🔨","🔑","🎯"],   a:"⚖️" },
      { q:"Which means 'no entry'? 🚫 ✅ 💚 ⭐",                      o:["🚫","✅","💚","⭐"],    a:"🚫" },
      { q:"🎵🎶🎵🎶 — what comes next?",                              o:["🎵","🎶","🎸","🎼"],    a:"🎵" },
    ],
    hard: [
      { q:"Which flag is shown for France? 🇫🇷 🇩🇪 🇮🇹 🇪🇸",        o:["🇫🇷","🇩🇪","🇮🇹","🇪🇸"],a:"🇫🇷" },
      { q:"🔴🟡🔵🟢🔴🟡🔵 — what comes next?",                      o:["🔴","🟡","🟢","🔵"],    a:"🟢" },
      { q:"Which symbol represents pi? π μ Σ Δ",                      o:["π","μ","Σ","Δ"],        a:"π" },
      { q:"Which emoji represents 'check mark'? ✅ ❌ ⚠️ 🔴",          o:["✅","❌","⚠️","🔴"],   a:"✅" },
      { q:"🌑🌒🌓🌔🌕 — what comes next?",                           o:["🌖","🌕","🌑","🌒"],    a:"🌖" },
      { q:"Which is a universal hazard symbol? ☢️ ✨ 💫 🌟",           o:["☢️","✨","💫","🌟"],   a:"☢️" },
      { q:"🎯🏹🎯🏹🎯 — what comes next?",                           o:["🎯","🏹","🎪","🏆"],    a:"🏹" },
      { q:"Which emoji shows scientific work? 🔬 🎨 🎭 🎲",           o:["🔬","🎨","🎭","🎲"],    a:"🔬" },
      { q:"ABC pattern: 🌸🌺🌼🌸🌺 — what comes next?",              o:["🌸","🌺","🌼","🌻"],    a:"🌼" },
      { q:"Which symbol means 'infinity'? ∞ Ω Φ Ψ",                   o:["∞","Ω","Φ","Ψ"],        a:"∞" },
      { q:"🧊💧♨️🧊💧 — what comes next?",                           o:["🧊","💧","♨️","❄️"],   a:"♨️" },
      { q:"Which is the recycle symbol? ♻️ 🔄 🔃 ↩️",                 o:["♻️","🔄","🔃","↩️"],   a:"♻️" },
      { q:"🌍🌎🌏🌍🌎 — what comes next?",                           o:["🌍","🌎","🌏","🌐"],    a:"🌏" },
      { q:"Which symbol means 'therefore' in maths? ∴ ∵ ∈ ∉",        o:["∴","∵","∈","∉"],        a:"∴" },
      { q:"Which represents 'heart' in card suits? ♠ ♥ ♦ ♣",         o:["♠","♥","♦","♣"],        a:"♥" },
    ],
  },

  /* ── 6. MEMORY 🧠 ────────────────────────────────────────────
     Style: recall patterns, what was first/last, sequences       */
  memory: {
    easy: [
      { q:"🐵🐶🐱 — which animal appeared first?",                    o:["🐵","🐶","🐱","All same"],a:"🐵" },
      { q:"Red, Blue, Green — which colour was mentioned last?",       o:["Red","Blue","Green","Yellow"],a:"Green" },
      { q:"1, 5, 3, 2 — which number was mentioned second?",          o:["1","5","3","2"],        a:"5" },
      { q:"Apple, Banana, Cherry — which came second?",               o:["Apple","Banana","Cherry","Mango"],a:"Banana" },
      { q:"🌟💫⭐ — which star shape appeared in the middle?",         o:["🌟","💫","⭐","All same"],a:"💫" },
      { q:"Cat, Dog, Bird — which animal came first?",                 o:["Cat","Dog","Bird","Fish"],a:"Cat" },
      { q:"4, 7, 2, 9 — which was the last number?",                  o:["4","7","2","9"],        a:"9" },
      { q:"Monday, Friday, Wednesday — which day was in the middle?",  o:["Monday","Friday","Wednesday","Tuesday"],a:"Wednesday" },
      { q:"🍎🍊🍋 — which fruit appeared last?",                      o:["🍎","🍊","🍋","🍇"],    a:"🍋" },
      { q:"Sun, Moon, Stars — which was mentioned first?",            o:["Sun","Moon","Stars","Cloud"],a:"Sun" },
      { q:"5, 3, 8, 1 — which was mentioned third?",                  o:["5","3","8","1"],        a:"8" },
      { q:"Square, Circle, Triangle — which shape was second?",        o:["Square","Circle","Triangle","Rectangle"],a:"Circle" },
      { q:"🐘🦁🐯 — which animal appeared in the middle?",             o:["🐘","🦁","🐯","🦒"],    a:"🦁" },
      { q:"June, March, August — which month was mentioned first?",   o:["June","March","August","July"],a:"June" },
      { q:"A, C, B, D — which letter appeared second?",               o:["A","C","B","D"],        a:"C" },
    ],
    medium: [
      { q:"🔴🟢🔵🟡 — which colour appeared third?",                  o:["🔴","🟢","🔵","🟡"],    a:"🔵" },
      { q:"12, 7, 19, 4, 23 — which was the middle number?",         o:["12","7","19","4"],       a:"19" },
      { q:"Lion, Tiger, Bear, Wolf — which was second?",              o:["Lion","Tiger","Bear","Wolf"],a:"Tiger" },
      { q:"Spring, Summer, Autumn — which season was last?",          o:["Spring","Summer","Autumn","Winter"],a:"Autumn" },
      { q:"🌙⭐☀️🌈 — which appeared second?",                        o:["🌙","⭐","☀️","🌈"],    a:"⭐" },
      { q:"Mercury, Venus, Earth, Mars — which is third?",            o:["Mercury","Venus","Earth","Mars"],a:"Earth" },
      { q:"34, 21, 55, 13, 8 — which was the fourth number?",        o:["34","21","55","13"],     a:"13" },
      { q:"Piano, Guitar, Drums, Flute — which came third?",          o:["Piano","Guitar","Drums","Flute"],a:"Drums" },
      { q:"Alpha, Beta, Gamma, Delta — which was second?",            o:["Alpha","Beta","Gamma","Delta"],a:"Beta" },
      { q:"🍕🍔🌮🍜 — which food was shown third?",                   o:["🍕","🍔","🌮","🍜"],    a:"🌮" },
      { q:"North, South, East, West — which direction was third?",    o:["North","South","East","West"],a:"East" },
      { q:"Hydrogen, Helium, Lithium — which element was last?",      o:["Hydrogen","Helium","Lithium","Carbon"],a:"Lithium" },
      { q:"8, 16, 4, 32, 2 — which was the second number?",          o:["8","16","4","32"],       a:"16" },
      { q:"Red, Orange, Yellow, Green — which colour was third?",     o:["Red","Orange","Yellow","Green"],a:"Yellow" },
      { q:"🐘🦒🦓🦁 — which animal appeared second?",                 o:["🐘","🦒","🦓","🦁"],    a:"🦒" },
    ],
    hard: [
      { q:"7, 14, 3, 28, 1, 21 — what was the fifth number?",        o:["1","3","7","14"],        a:"1" },
      { q:"Which comes 4th: Mercury, Venus, Earth, Mars, Jupiter?",   o:["Earth","Mars","Jupiter","Venus"],a:"Mars" },
      { q:"A, E, I, O, U — which vowel was in the middle?",           o:["A","E","I","O"],         a:"I" },
      { q:"🌹🌷🌻🌸🌼 — which flower was fourth?",                    o:["🌹","🌷","🌻","🌸"],     a:"🌸" },
      { q:"12, 6, 18, 3, 24, 9 — which was the last number?",        o:["3","9","18","24"],       a:"9" },
      { q:"First 6 US presidents: Washington, Adams, Jefferson, Madison, Monroe, Adams — who was 4th?", o:["Washington","Jefferson","Madison","Monroe"],a:"Madison" },
      { q:"Do, Re, Mi, Fa, Sol, La — which note was fifth?",         o:["Mi","Fa","Sol","La"],    a:"Sol" },
      { q:"🔴🟠🟡🟢🔵🟣 — which colour was in position 4?",          o:["🟡","🟢","🔵","🟣"],    a:"🟢" },
      { q:"Newton, Einstein, Darwin, Curie, Tesla — who was third?",  o:["Newton","Einstein","Darwin","Curie"],a:"Darwin" },
      { q:"2, 4, 8, 16, 32, 64 — which number was in the 5th position?",o:["16","32","64","8"],   a:"32" },
      { q:"AEIOU in order — which vowel is 4th?",                     o:["A","E","I","O"],         a:"O" },
      { q:"Spring, Summer, Autumn, Winter — which season is 2nd?",    o:["Spring","Summer","Autumn","Winter"],a:"Summer" },
      { q:"1st, 2nd, 3rd... 8th in Roman: I,II,III,IV,V,VI,VII — what is 7th?",o:["V","VI","VII","VIII"],a:"VII" },
      { q:"Chess pieces: King, Queen, Rook, Bishop, Knight, Pawn — what is 4th?",o:["Rook","Bishop","Knight","Pawn"],a:"Bishop" },
      { q:"RGB: Red=1, Green=2, Blue=3. Mixed order 3,1,2 gives?",    o:["BGR","RBG","GBR","BRG"],a:"BRG" },
    ],
  },

  /* ── 7. SPEED ⚡ ──────────────────────────────────────────────
     Style: quick-fire mental maths, fast yes/no               */
  speed: {
    easy: [
      { q:"⚡ 2 + 2 = ?",                                              o:["3","4","5","6"],        a:"4" },
      { q:"⚡ Is 8 an even number?",                                   o:["Yes","No","Maybe","Sometimes"],a:"Yes" },
      { q:"⚡ 10 − 3 = ?",                                             o:["6","7","8","9"],        a:"7" },
      { q:"⚡ Is 5 odd or even?",                                       o:["Odd","Even","Both","Neither"],a:"Odd" },
      { q:"⚡ 3 × 3 = ?",                                              o:["6","8","9","12"],       a:"9" },
      { q:"⚡ Is 12 divisible by 3?",                                  o:["Yes","No","Maybe","Sometimes"],a:"Yes" },
      { q:"⚡ 15 ÷ 5 = ?",                                             o:["2","3","4","5"],        a:"3" },
      { q:"⚡ Is 7 a prime number?",                                   o:["Yes","No","Maybe","Sometimes"],a:"Yes" },
      { q:"⚡ 6 + 7 = ?",                                              o:["12","13","14","15"],    a:"13" },
      { q:"⚡ Is 9 even?",                                              o:["Yes","No","Maybe","Sometimes"],a:"No" },
      { q:"⚡ 4 × 5 = ?",                                              o:["18","19","20","21"],    a:"20" },
      { q:"⚡ Is 1 a prime number?",                                   o:["Yes","No","Maybe","Sometimes"],a:"No" },
      { q:"⚡ 20 − 8 = ?",                                             o:["10","11","12","13"],    a:"12" },
      { q:"⚡ Is 100 divisible by 4?",                                 o:["Yes","No","Maybe","Sometimes"],a:"Yes" },
      { q:"⚡ 8 ÷ 2 = ?",                                              o:["2","3","4","5"],        a:"4" },
    ],
    medium: [
      { q:"⚡ 13 × 7 = ?",                                             o:["89","91","93","95"],    a:"91" },
      { q:"⚡ Is 97 a prime number?",                                  o:["Yes","No","Maybe","Sometimes"],a:"Yes" },
      { q:"⚡ 144 ÷ 12 = ?",                                           o:["10","11","12","13"],    a:"12" },
      { q:"⚡ Is 2 the only even prime?",                              o:["Yes","No","Maybe","Sometimes"],a:"Yes" },
      { q:"⚡ 56 + 47 = ?",                                            o:["100","102","103","105"],a:"103" },
      { q:"⚡ Is 51 divisible by 3?",                                  o:["Yes","No","Maybe","Sometimes"],a:"Yes" },
      { q:"⚡ 15² = ?",                                                o:["215","220","225","230"],a:"225" },
      { q:"⚡ Is 0 a natural number?",                                 o:["Yes","No","Depends","Maybe"],a:"No" },
      { q:"⚡ 84 ÷ 7 = ?",                                             o:["10","11","12","13"],    a:"12" },
      { q:"⚡ Is 49 a perfect square?",                                o:["Yes","No","Maybe","Sometimes"],a:"Yes" },
      { q:"⚡ 99 × 11 = ?",                                            o:["1079","1089","1099","1109"],a:"1089" },
      { q:"⚡ Is 81 a perfect cube?",                                  o:["Yes","No","Maybe","Sometimes"],a:"No" },
      { q:"⚡ 7 × 8 = ?",                                              o:["54","55","56","57"],    a:"56" },
      { q:"⚡ Is 64 both a perfect square AND cube?",                  o:["Yes","No","Maybe","Sometimes"],a:"Yes" },
      { q:"⚡ √169 = ?",                                               o:["11","12","13","14"],    a:"13" },
    ],
    hard: [
      { q:"⚡ 17 × 19 = ?",                                            o:["321","322","323","324"],a:"323" },
      { q:"⚡ Is 1 001 a prime number?",                               o:["Yes","No","Maybe","Sometimes"],a:"No" },
      { q:"⚡ 2⁸ = ?",                                                 o:["128","256","512","1024"],a:"256" },
      { q:"⚡ Is 999 divisible by 9?",                                 o:["Yes","No","Maybe","Sometimes"],a:"Yes" },
      { q:"⚡ √(144 + 25) = ?",                                        o:["11","12","13","14"],    a:"13" },
      { q:"⚡ 23 × 23 = ?",                                            o:["519","528","529","539"],a:"529" },
      { q:"⚡ Is π rational?",                                          o:["Yes","No","Maybe","Sometimes"],a:"No" },
      { q:"⚡ 11³ = ?",                                                 o:["1221","1331","1441","1551"],a:"1331" },
      { q:"⚡ LCM of 12 and 18 = ?",                                   o:["24","36","48","72"],    a:"36" },
      { q:"⚡ GCD of 48 and 36 = ?",                                   o:["6","8","12","16"],      a:"12" },
      { q:"⚡ Is √2 an irrational number?",                            o:["Yes","No","Maybe","Sometimes"],a:"Yes" },
      { q:"⚡ 101 × 99 = ?",                                           o:["9 899","9 999","10 099","10 199"],a:"9 999" },
      { q:"⚡ 3⁵ = ?",                                                  o:["183","213","243","273"],a:"243" },
      { q:"⚡ Is 0.999... equal to 1?",                                o:["Yes","No","Approximately","Never"],a:"Yes" },
      { q:"⚡ √(3² + 4²) = ?",                                         o:["4","5","6","7"],        a:"5" },
    ],
  },

  /* ── 8. COMPARISON ⚖️ ────────────────────────────────────────
     Style: bigger/smaller/heavier/more, tricky comparisons       */
  comparison: {
    easy: [
      { q:"⚖️ Which is bigger: 5 or 8?",                               o:["5","8","Both same","Cannot say"],a:"8" },
      { q:"⚖️ Which is heavier: 1 kg iron or 1 kg cotton?",            o:["Iron","Cotton","Both same","Depends"],a:"Both same" },
      { q:"⚖️ Which is longer: 1 metre or 1 km?",                      o:["1 metre","1 km","Both same","Depends"],a:"1 km" },
      { q:"⚖️ Which is more: 12 apples or 7 apples?",                  o:["12","7","Both same","Cannot say"],a:"12" },
      { q:"⚖️ Which is colder: 0°C or 10°C?",                          o:["0°C","10°C","Both same","Cannot say"],a:"0°C" },
      { q:"⚖️ Which is faster: walking or running?",                    o:["Walking","Running","Both same","Depends"],a:"Running" },
      { q:"⚖️ Which holds more: a cup or a bucket?",                    o:["Cup","Bucket","Both same","Depends"],a:"Bucket" },
      { q:"⚖️ Which is taller: a mouse or an elephant?",               o:["Mouse","Elephant","Both same","Depends"],a:"Elephant" },
      { q:"⚖️ Which is smaller: 0.5 or 0.9?",                          o:["0.5","0.9","Both same","Cannot say"],a:"0.5" },
      { q:"⚖️ Which is louder: a whisper or a shout?",                  o:["Whisper","Shout","Both same","Depends"],a:"Shout" },
      { q:"⚖️ Which is more: 3 dozens or 40?",                         o:["3 dozens","40","Both same","Cannot say"],a:"Both same" },
      { q:"⚖️ Which is brighter: candle or sunlight?",                  o:["Candle","Sunlight","Both same","Depends"],a:"Sunlight" },
      { q:"⚖️ Which is heavier: a feather or a rock?",                  o:["Feather","Rock","Both same","Depends"],a:"Rock" },
      { q:"⚖️ Which is greater: ½ or ¼?",                              o:["½","¼","Both same","Cannot say"],a:"½" },
      { q:"⚖️ Which is closer: 1 km or 1 mile?",                       o:["1 km","1 mile","Both same","Cannot say"],a:"1 km" },
    ],
    medium: [
      { q:"⚖️ Which is greater: 3/4 or 5/8?",                          o:["3/4","5/8","Both equal","Cannot say"],a:"3/4" },
      { q:"⚖️ Which weighs more: 500 g or half a kilogram?",           o:["500 g","Half kg","Both same","Depends"],a:"Both same" },
      { q:"⚖️ Which is faster: sound or light?",                        o:["Sound","Light","Both same","Depends"],a:"Light" },
      { q:"⚖️ Which is larger area: 1 m² or 100 cm²?",                 o:["1 m²","100 cm²","Both equal","Cannot say"],a:"1 m²" },
      { q:"⚖️ Which is closer to 10: 7.5 or 12.1?",                    o:["7.5","12.1","Both same","Cannot say"],a:"7.5" },
      { q:"⚖️ Which is more: 0.75 or 3/4?",                            o:["0.75","3/4","Both equal","Cannot say"],a:"Both equal" },
      { q:"⚖️ 1 litre of water vs 1 litre of oil. Which is heavier?",  o:["Water","Oil","Both same","Depends"],a:"Water" },
      { q:"⚖️ Which is longer: 1 hour or 90 minutes?",                 o:["1 hour","90 minutes","Both same","Depends"],a:"90 minutes" },
      { q:"⚖️ Which is greater: 2³ or 3²?",                            o:["2³","3²","Both equal","Cannot say"],a:"Both equal" },
      { q:"⚖️ Which is faster: 60 km/h or 20 m/s?",                   o:["60 km/h","20 m/s","Both same","Cannot say"],a:"20 m/s" },
      { q:"⚖️ Which is larger: 40% of 200 or 60% of 120?",             o:["40% of 200","60% of 120","Both equal","Cannot say"],a:"Both equal" },
      { q:"⚖️ Which angle is larger: 91° or a right angle?",           o:["91°","Right angle","Both equal","Cannot say"],a:"91°" },
      { q:"⚖️ Which is bigger: √2 or √3?",                             o:["√2","√3","Both equal","Cannot say"],a:"√3" },
      { q:"⚖️ Which is more: 10% of 500 or 50% of 100?",               o:["10% of 500","50% of 100","Both equal","Cannot say"],a:"Both equal" },
      { q:"⚖️ Which holds more data: 1 MB or 1024 KB?",                o:["1 MB","1024 KB","Both equal","Depends"],a:"Both equal" },
    ],
    hard: [
      { q:"⚖️ Which is greater: e (≈2.718) or π/1.155 (≈2.72)?",      o:["e","π/1.155","Both equal","Cannot say"],a:"π/1.155" },
      { q:"⚖️ Which is larger: log₁₀(1000) or log₂(8)?",              o:["log₁₀(1000)","log₂(8)","Both equal","Cannot say"],a:"Both equal" },
      { q:"⚖️ 1 kg of feathers vs 1 kg of lead in a vacuum?",          o:["Feathers","Lead","Both same","Depends on gravity"],a:"Both same" },
      { q:"⚖️ Which is greater: 0.1 + 0.2 or 0.3 in a computer?",     o:["0.1+0.2","0.3","Both equal","Depends"],a:"0.1+0.2" },
      { q:"⚖️ Which is larger: 2¹⁰ or 10³?",                          o:["2¹⁰","10³","Both equal","Cannot say"],a:"2¹⁰" },
      { q:"⚖️ Which is faster: 100 km/h or 28 m/s?",                  o:["100 km/h","28 m/s","Both same","Cannot say"],a:"100 km/h" },
      { q:"⚖️ Which is more: sin(90°) or cos(0°)?",                   o:["sin(90°)","cos(0°)","Both equal","Cannot say"],a:"Both equal" },
      { q:"⚖️ Which has more area: circle r=7 or square side=12?",     o:["Circle r=7","Square side=12","Both equal","Cannot say"],a:"Square side=12" },
      { q:"⚖️ Longer: 1 light-year or 1 parsec?",                      o:["1 light-year","1 parsec","Both equal","Depends"],a:"1 parsec" },
      { q:"⚖️ Greater: (0.99)¹⁰⁰ or (0.01)?",                         o:["(0.99)¹⁰⁰","0.01","Both equal","Cannot say"],a:"(0.99)¹⁰⁰" },
      { q:"⚖️ Which is bigger: √(2+√2) or ³√7?",                      o:["√(2+√2)","³√7","Both equal","Cannot say"],a:"³√7" },
      { q:"⚖️ More digits: 100! or 2¹⁰⁰?",                            o:["100!","2¹⁰⁰","Both equal","Cannot say"],a:"100!" },
      { q:"⚖️ Greater: 1/e or log₁₀(e)?",                             o:["1/e","log₁₀(e)","Both equal","Cannot say"],a:"1/e" },
      { q:"⚖️ Which probability is larger: P(head in 3 flips) or 50%?",o:["P(head in 3)","50%","Both equal","Cannot say"],a:"50%" },
      { q:"⚖️ More: ∑(1/n²) for n=1 to ∞ or 2?",                     o:["∑(1/n²)","2","Both equal","Cannot say"],a:"2" },
    ],
  },

  /* ── 9. SEQUENCE 📅 ──────────────────────────────────────────
     Style: days, months, alphabet order, what comes next         */
  sequence: {
    easy: [
      { q:"📅 Monday → what day comes next?",                         o:["Sunday","Monday","Tuesday","Wednesday"],a:"Tuesday" },
      { q:"📅 January, February, ?",                                  o:["March","April","May","June"],a:"March" },
      { q:"📅 A, B, C, D, ?",                                         o:["D","E","F","G"],         a:"E" },
      { q:"📅 Spring, Summer, ?, Winter",                             o:["Spring","Autumn","Rain","Snow"],a:"Autumn" },
      { q:"📅 1st, 2nd, 3rd, ?",                                      o:["4th","5th","6th","7th"],  a:"4th" },
      { q:"📅 Sunday is the 1st day. What is the 4th?",               o:["Monday","Tuesday","Wednesday","Thursday"],a:"Wednesday" },
      { q:"📅 Breakfast, Lunch, ?",                                   o:["Snack","Dinner","Sleep","Dessert"],a:"Dinner" },
      { q:"📅 Baby, Child, Teen, ?",                                   o:["Old","Adult","Elderly","Ancient"],a:"Adult" },
      { q:"📅 North, East, South, ?",                                  o:["Up","Down","West","Left"],a:"West" },
      { q:"📅 Morning, Afternoon, Evening, ?",                         o:["Midnight","Night","Dusk","Dawn"],a:"Night" },
      { q:"📅 Egg, Caterpillar, Chrysalis, ?",                         o:["Ant","Butterfly","Bee","Fly"],a:"Butterfly" },
      { q:"📅 January has 31 days. Next 31-day month is?",            o:["February","March","April","May"],a:"March" },
      { q:"📅 Puppy → Dog. Kitten → ?",                               o:["Tiger","Cat","Lion","Bear"],a:"Cat" },
      { q:"📅 0, 1, 2, 3 — what comes before 0?",                    o:["-1","0","1","2"],         a:"-1" },
      { q:"📅 Seed → Sprout → Sapling → ?",                           o:["Flower","Tree","Leaf","Root"],a:"Tree" },
    ],
    medium: [
      { q:"📅 What is the 10th month of the year?",                   o:["September","October","November","December"],a:"October" },
      { q:"📅 Next in Olympic cycle: 2020, 2024, ?",                  o:["2026","2028","2030","2032"],a:"2028" },
      { q:"📅 DNA → RNA → ?",                                          o:["ATP","Protein","Lipid","Carbohydrate"],a:"Protein" },
      { q:"📅 Primary → Secondary → Tertiary → ?",                    o:["Quaternary","Final","Ultimate","Top"],a:"Quaternary" },
      { q:"📅 Solid → Liquid → ? (heating continues)",                o:["Gas","Plasma","Steam","Ice"],a:"Gas" },
      { q:"📅 Byte → Kilobyte → Megabyte → ?",                        o:["Gigabyte","Terabyte","Petabyte","Exabyte"],a:"Gigabyte" },
      { q:"📅 Larva → Pupa → ?",                                       o:["Egg","Caterpillar","Adult","Chrysalis"],a:"Adult" },
      { q:"📅 1st gen → 2nd gen. In tech, what follows 4G?",          o:["4.5G","5G","6G","4G+"],   a:"5G" },
      { q:"📅 Stone Age → Bronze Age → ?",                             o:["Iron Age","Steel Age","Digital Age","Ice Age"],a:"Iron Age" },
      { q:"📅 Single → Double → Triple → ?",                           o:["Quadruple","Multiple","Fifth","Half"],a:"Quadruple" },
      { q:"📅 January=1, February=2... September = ?",                o:["7","8","9","10"],         a:"9" },
      { q:"📅 km → m → cm → ?",                                        o:["mm","nm","pm","dm"],     a:"mm" },
      { q:"📅 Tadpole → Froglet → ?",                                  o:["Fish","Toad","Frog","Newt"],a:"Frog" },
      { q:"📅 Trillion → Billion → Million → ?",                       o:["Thousand","Hundred","Ten","Unit"],a:"Thousand" },
      { q:"📅 King → Prince → ? (next generation)",                   o:["Duke","Earl","Marquess","Baron"],a:"Duke" },
    ],
    hard: [
      { q:"📅 In binary: 0001, 0010, 0011, 0100, ?",                  o:["0101","0110","0111","1000"],a:"0101" },
      { q:"📅 Geological: Triassic → Jurassic → ?",                   o:["Cretaceous","Permian","Cambrian","Devonian"],a:"Cretaceous" },
      { q:"📅 Musical: Do, Re, Mi, Fa, Sol, La, ?",                   o:["Si/Ti","Lo","Ba","Na"],   a:"Si/Ti" },
      { q:"📅 Tax bracket sequence: 0%, 20%, 40%, ?",                 o:["45%","50%","55%","60%"],  a:"45%" },
      { q:"📅 Evolution: Fish → Amphibian → Reptile → ?",             o:["Mammal","Bird","Insect","Both mammal and bird"],a:"Both mammal and bird" },
      { q:"📅 pH scale: Very acidic(0) → Neutral(7) → Very alkaline(?)",o:["10","12","14","16"],   a:"14" },
      { q:"📅 OSI Model layers 1,2,3 are Physical, Data Link, ?",     o:["Transport","Network","Session","Application"],a:"Network" },
      { q:"📅 Plutonium → Uranium → Thorium (decay chain): what's before Plutonium?",o:["Curium","Neptunium","Americium","Californium"],a:"Curium" },
      { q:"📅 0D Point → 1D Line → 2D Plane → 3D Solid → ?",          o:["4D","5D","Hyperplane","Tesseract"],a:"4D" },
      { q:"📅 IPv4 → IPv6. How many bits in IPv6 address?",           o:["64","96","128","256"],    a:"128" },
      { q:"📅 Andromeda galaxy distance: 2.537 million light-years. Next nearest large galaxy?",o:["Milky Way","Triangulum","Pinwheel","Sombrero"],a:"Triangulum" },
      { q:"📅 Sorting: Bubble → Merge → Quick → ? (fastest average)",  o:["Heap","Radix","Shell","Counting"],a:"Radix" },
      { q:"📅 React → Angular → Vue → ? (JS frameworks trend)",        o:["Svelte","Ember","Backbone","jQuery"],a:"Svelte" },
      { q:"📅 Kelvin: 0K = −273.15°C. At what K is water 100°C?",    o:["373 K","373.15 K","373.16 K","374 K"],a:"373.15 K" },
      { q:"📅 Hadron → Baryon → Proton/Neutron → ? (substructure)",   o:["Quark","Electron","Neutrino","Photon"],a:"Quark" },
    ],
  },

  /* ── 10. WORD 📝 ─────────────────────────────────────────────
     Style: vocabulary, opposites, which is a fruit/animal, spelling */
  word: {
    easy: [
      { q:"📝 Opposite of 'big'?",                                    o:["Large","Small","Tall","Wide"],a:"Small" },
      { q:"📝 Which is a fruit: Carrot, Apple, Potato, Onion?",       o:["Carrot","Apple","Potato","Onion"],a:"Apple" },
      { q:"📝 Another word for 'happy'?",                              o:["Sad","Angry","Joyful","Tired"],a:"Joyful" },
      { q:"📝 Opposite of 'hot'?",                                    o:["Warm","Cool","Cold","Freezing"],a:"Cold" },
      { q:"📝 Which is NOT a colour: Red, Big, Blue, Green?",         o:["Red","Big","Blue","Green"],a:"Big" },
      { q:"📝 Correct spelling?",                                     o:["Freind","Friend","Frend","Feiend"],a:"Friend" },
      { q:"📝 Opposite of 'day'?",                                    o:["Evening","Dusk","Night","Dawn"],a:"Night" },
      { q:"📝 Which is an animal: Chair, Dog, Table, Door?",          o:["Chair","Dog","Table","Door"],a:"Dog" },
      { q:"📝 Another word for 'fast'?",                               o:["Slow","Quick","Lazy","Gentle"],a:"Quick" },
      { q:"📝 Opposite of 'up'?",                                     o:["Left","Right","Down","Side"],a:"Down" },
      { q:"📝 Which is a vegetable: Apple, Mango, Carrot, Grape?",    o:["Apple","Mango","Carrot","Grape"],a:"Carrot" },
      { q:"📝 Correct spelling?",                                     o:["Becuase","Because","Becasue","Becouse"],a:"Because" },
      { q:"📝 Another word for 'small'?",                              o:["Large","Tiny","Giant","Big"],a:"Tiny" },
      { q:"📝 Opposite of 'loud'?",                                   o:["Noisy","Quiet","Soft","Clear"],a:"Quiet" },
      { q:"📝 Which is a bird: Lion, Eagle, Tiger, Shark?",           o:["Lion","Eagle","Tiger","Shark"],a:"Eagle" },
    ],
    medium: [
      { q:"📝 Synonym of 'brave'?",                                   o:["Cowardly","Timid","Courageous","Weak"],a:"Courageous" },
      { q:"📝 What does 'abundant' mean?",                            o:["Rare","Plentiful","Small","Hidden"],a:"Plentiful" },
      { q:"📝 Correct spelling?",                                     o:["Accomodate","Accommodate","Acommodate","Acomodate"],a:"Accommodate" },
      { q:"📝 Antonym of 'ancient'?",                                 o:["Old","Historic","Modern","Aged"],a:"Modern" },
      { q:"📝 What does 'transparent' mean?",                         o:["Invisible","See-through","Colourful","Opaque"],a:"See-through" },
      { q:"📝 Correct spelling?",                                     o:["Definately","Definitely","Definatly","Defenitely"],a:"Definitely" },
      { q:"📝 Word that replaces a noun is called a?",                o:["Verb","Adjective","Pronoun","Conjunction"],a:"Pronoun" },
      { q:"📝 What does 'ferocious' mean?",                           o:["Gentle","Fierce","Timid","Friendly"],a:"Fierce" },
      { q:"📝 Correct spelling?",                                     o:["Wierd","Weird","Wired","Wirde"],a:"Weird" },
      { q:"📝 Homophone of 'their'?",                                 o:["Thier","Ther","There","Thear"],a:"There" },
      { q:"📝 What does 'reluctant' mean?",                           o:["Eager","Willing","Unwilling","Happy"],a:"Unwilling" },
      { q:"📝 Plural of 'child'?",                                    o:["Childs","Childen","Children","Childer"],a:"Children" },
      { q:"📝 Correct spelling?",                                     o:["Recieve","Recive","Receive","Receeve"],a:"Receive" },
      { q:"📝 Antonym of 'generous'?",                                o:["Kind","Selfish","Wealthy","Giving"],a:"Selfish" },
      { q:"📝 Past tense of 'swim'?",                                 o:["Swimmed","Swum","Swam","Swimed"],a:"Swam" },
    ],
    hard: [
      { q:"📝 'Break a leg' means?",                                  o:["Get injured","Good luck","Stop dancing","Run away"],a:"Good luck" },
      { q:"📝 Root word 'port' means?",                               o:["Write","Carry","See","Build"],a:"Carry" },
      { q:"📝 'The sun smiled down' is an example of?",               o:["Simile","Personification","Metaphor","Hyperbole"],a:"Personification" },
      { q:"📝 'As brave as a lion' is a?",                            o:["Metaphor","Simile","Idiom","Alliteration"],a:"Simile" },
      { q:"📝 Suffix '-ology' means?",                                o:["Fear of","The study of","The love of","To do with"],a:"The study of" },
      { q:"📝 'Ephemeral' means?",                                    o:["Lasting forever","Short-lived","Very large","Colourful"],a:"Short-lived" },
      { q:"📝 What does 'philanthropy' mean?",                        o:["Love of money","Love of humanity","Fear of crowds","Love of animals"],a:"Love of humanity" },
      { q:"📝 'Serendipity' means?",                                  o:["Sadness","A lucky discovery by chance","Hard work","Confusion"],a:"A lucky discovery by chance" },
      { q:"📝 Latin 'scrib/script' means?",                           o:["See","Run","Write","Build"],a:"Write" },
      { q:"📝 Oxymoron combines two?",                                o:["Similar words","Contradictory words","Long words","Short words"],a:"Contradictory words" },
      { q:"📝 Subjunctive mood expresses?",                           o:["Facts","Wishes or hypotheticals","Past events","Questions"],a:"Wishes or hypotheticals" },
      { q:"📝 Prefix 'un-' means?",                                   o:["Again","Not","Before","Together"],a:"Not" },
      { q:"📝 'Peter Piper picked a peck' is?",                       o:["Alliteration","Rhyme","Onomatopoeia","Metaphor"],a:"Alliteration" },
      { q:"📝 Word with same spelling, different meaning is a?",      o:["Homophone","Homonym","Synonym","Antonym"],a:"Homonym" },
      { q:"📝 'I've told you a million times!' is an example of?",    o:["Simile","Metaphor","Hyperbole","Alliteration"],a:"Hyperbole" },
    ],
  },

  /* ── 11. ANIMALS 🐾 ──────────────────────────────────────────
     Style: fun animal facts, which animal/what sound/habitat      */
  animals: {
    easy: [
      { q:"🐾 Which animal can fly? 🐟 🐕 🦅 🐄",                    o:["🐟","🐕","🦅","🐄"],    a:"🦅" },
      { q:"🐾 🐶 vs 🐦 — which can sing?",                            o:["🐶","🐦","Both","Neither"],a:"🐦" },
      { q:"🐾 What sound does a cow make?",                            o:["Baa","Moo","Woof","Meow"],a:"Moo" },
      { q:"🐾 Which animal lives in water: Cat, Fish, Dog, Rabbit?",  o:["Cat","Fish","Dog","Rabbit"],a:"Fish" },
      { q:"🐾 What do bees make?",                                    o:["Milk","Silk","Honey","Wax"],a:"Honey" },
      { q:"🐾 Which is the largest animal on land?",                  o:["Giraffe","Elephant","Hippo","Rhino"],a:"Elephant" },
      { q:"🐾 What does a caterpillar turn into?",                    o:["Beetle","Butterfly","Ant","Spider"],a:"Butterfly" },
      { q:"🐾 Which animal has a pouch for its baby?",                o:["Lion","Kangaroo","Tiger","Wolf"],a:"Kangaroo" },
      { q:"🐾 What sound does a snake make?",                         o:["Roar","Bark","Hiss","Meow"],a:"Hiss" },
      { q:"🐾 Which bird cannot fly?",                                o:["Eagle","Sparrow","Penguin","Parrot"],a:"Penguin" },
      { q:"🐾 Which animal is known as 'King of the Jungle'?",        o:["Tiger","Bear","Lion","Cheetah"],a:"Lion" },
      { q:"🐾 What do pandas eat?",                                   o:["Meat","Fish","Bamboo","Grass"],a:"Bamboo" },
      { q:"🐾 Which is the fastest land animal?",                     o:["Lion","Horse","Cheetah","Leopard"],a:"Cheetah" },
      { q:"🐾 How many legs does a spider have?",                     o:["4","6","8","10"],           a:"8" },
      { q:"🐾 Which animal sleeps standing up?",                      o:["Dog","Cat","Horse","Rabbit"],a:"Horse" },
    ],
    medium: [
      { q:"🐾 Which mammal lays eggs?",                               o:["Bat","Whale","Platypus","Dolphin"],a:"Platypus" },
      { q:"🐾 Which animal has the longest neck?",                    o:["Elephant","Giraffe","Camel","Ostrich"],a:"Giraffe" },
      { q:"🐾 A baby kangaroo is called a?",                          o:["Cub","Joey","Kitten","Foal"],a:"Joey" },
      { q:"🐾 Which is NOT a reptile: Crocodile, Snake, Frog, Lizard?",o:["Crocodile","Snake","Frog","Lizard"],a:"Frog" },
      { q:"🐾 How long is an elephant pregnant (approx)?",             o:["3 months","9 months","18 months","22 months"],a:"22 months" },
      { q:"🐾 Which animal can change its colour?",                   o:["Shark","Chameleon","Tiger","Eagle"],a:"Chameleon" },
      { q:"🐾 What is a group of wolves called?",                     o:["Pack","Pride","Flock","Herd"],a:"Pack" },
      { q:"🐾 Which animal has the biggest brain relative to body?",  o:["Elephant","Dolphin","Human","Chimpanzee"],a:"Human" },
      { q:"🐾 Which is the only mammal capable of true flight?",      o:["Flying squirrel","Bat","Sugar glider","Colugo"],a:"Bat" },
      { q:"🐾 What is the collective name for a group of fish?",      o:["Herd","Pack","School","Pride"],a:"School" },
      { q:"🐾 Which animal has the largest eyes relative to its body?",o:["Owl","Eagle","Tarsier","Cat"],a:"Tarsier" },
      { q:"🐾 Which bird can mimic human speech best?",               o:["Parrot","Crow","Canary","Robin"],a:"Parrot" },
      { q:"🐾 How many hearts does an octopus have?",                 o:["1","2","3","4"],             a:"3" },
      { q:"🐾 Which is the longest snake?",                           o:["Cobra","Python","Anaconda","Boa"],a:"Python" },
      { q:"🐾 What do sharks use to detect blood from far away?",     o:["Eyes","Ears","Nose/Smell","Skin"],a:"Nose/Smell" },
    ],
    hard: [
      { q:"🐾 What is the scientific name for a house cat?",          o:["Panthera leo","Felis catus","Canis lupus","Ursus arctos"],a:"Felis catus" },
      { q:"🐾 How many chambers does a cow's stomach have?",          o:["2","3","4","5"],             a:"4" },
      { q:"🐾 Which animal has the highest blood pressure?",          o:["Elephant","Giraffe","Blue whale","Cheetah"],a:"Giraffe" },
      { q:"🐾 What is the gestation period of an elephant in months?",o:["18","20","22","24"],         a:"22" },
      { q:"🐾 Which bird has the largest wingspan?",                  o:["Eagle","Condor","Albatross","Pelican"],a:"Albatross" },
      { q:"🐾 What is the collective noun for a group of owls?",      o:["Pack","Flock","Parliament","Pride"],a:"Parliament" },
      { q:"🐾 Which animal has the most teeth?",                      o:["Great white shark","Snail","Catfish","Dolphin"],a:"Snail" },
      { q:"🐾 How does a starfish regenerate?",                       o:["Eggs","Budding","Regeneration from arms","Spores"],a:"Regeneration from arms" },
      { q:"🐾 Which mammal has the slowest metabolism?",              o:["Sloth","Koala","Panda","Hedgehog"],a:"Sloth" },
      { q:"🐾 Mantis shrimp can see how many colours?",              o:["3","16","100","hundreds of"],a:"16" },
      { q:"🐾 Which animal can survive being frozen solid?",          o:["Arctic fox","Tardigrade","Wood frog","Polar bear"],a:"Wood frog" },
      { q:"🐾 What percentage of a cat's waking time is spent grooming?",o:["10%","20%","30%","50%"],a:"30%" },
      { q:"🐾 Which animal has a tongue longer than its body?",       o:["Anteater","Chameleon","Giraffe","Frog"],a:"Chameleon" },
      { q:"🐾 How many eyes does a bee have?",                        o:["2","4","5","6"],             a:"5" },
      { q:"🐾 Which is the only lizard that can blink?",              o:["Iguana","Gecko","Chameleon","Monitor lizard"],a:"Gecko" },
    ],
  },

  /* ── 12. COLORS 🎨 ───────────────────────────────────────────
     Style: colour recognition, mixing, what colour is X          */
  colors: {
    easy: [
      { q:"🎨 What colour is the sky on a clear day?",                o:["Green","Blue","Yellow","Red"],a:"Blue" },
      { q:"🎨 🔴 vs 🔵 — which is red?",                              o:["🔴","🔵","Both","Neither"],a:"🔴" },
      { q:"🎨 What colour is grass?",                                  o:["Blue","Yellow","Green","Brown"],a:"Green" },
      { q:"🎨 What colour is the sun?",                               o:["Red","Blue","Yellow","Green"],a:"Yellow" },
      { q:"🎨 What colour do you get mixing red and blue?",           o:["Green","Orange","Purple","Brown"],a:"Purple" },
      { q:"🎨 What colour is a ripe banana?",                         o:["Green","Red","Yellow","Blue"],a:"Yellow" },
      { q:"🎨 What colour is snow?",                                   o:["Grey","White","Cream","Silver"],a:"White" },
      { q:"🎨 What colour is a tomato?",                              o:["Green","Blue","Orange","Red"],a:"Red" },
      { q:"🎨 What colour do you get mixing yellow and blue?",        o:["Red","Purple","Green","Orange"],a:"Green" },
      { q:"🎨 What colour is chocolate?",                              o:["Black","Red","Brown","Purple"],a:"Brown" },
      { q:"🎨 What colour is a flamingo?",                            o:["White","Pink","Yellow","Orange"],a:"Pink" },
      { q:"🎨 What colour do you get mixing red and yellow?",         o:["Purple","Orange","Green","Brown"],a:"Orange" },
      { q:"🎨 What colour is coal?",                                   o:["Grey","Brown","Black","Dark blue"],a:"Black" },
      { q:"🎨 What colour is a zebra's stripes?",                     o:["Black and white","Brown and white","Grey and black","Black and grey"],a:"Black and white" },
      { q:"🎨 How many colours are in a rainbow?",                    o:["5","6","7","8"],             a:"7" },
    ],
    medium: [
      { q:"🎨 What are the three primary colours?",                   o:["Red, Blue, Green","Red, Yellow, Blue","Red, Yellow, Green","Orange, Blue, Green"],a:"Red, Yellow, Blue" },
      { q:"🎨 What colour do you get mixing all primary colours?",    o:["Black","White","Brown","Grey"],a:"Brown" },
      { q:"🎨 What colour is opposite to red on the colour wheel?",   o:["Orange","Purple","Green","Blue"],a:"Green" },
      { q:"🎨 What colour results from blue + green?",                o:["Purple","Teal/Cyan","Yellow","Brown"],a:"Teal/Cyan" },
      { q:"🎨 What is a 'warm' colour group?",                        o:["Blue, Green, Purple","Red, Orange, Yellow","Pink, Purple, Blue","Green, Blue, Teal"],a:"Red, Orange, Yellow" },
      { q:"🎨 What does 'magenta' look like?",                        o:["Dark blue","Pale yellow","Pinkish-red","Dark green"],a:"Pinkish-red" },
      { q:"🎨 Black absorbs all light. White does what?",             o:["Absorbs all light","Reflects all light","Emits light","Blocks light"],a:"Reflects all light" },
      { q:"🎨 What colour is cyan closest to?",                       o:["Red","Yellow","Blue-green","Purple"],a:"Blue-green" },
      { q:"🎨 In RGB model, max red+max green = ?",                   o:["White","Cyan","Yellow","Magenta"],a:"Yellow" },
      { q:"🎨 What colour is 'vermillion'?",                          o:["Deep blue","Bright orange-red","Pale yellow","Dark green"],a:"Bright orange-red" },
      { q:"🎨 Mixing complementary colours gives?",                   o:["Brighter colour","White","Neutral/brown/grey","Black"],a:"Neutral/brown/grey" },
      { q:"🎨 What colour is 'chartreuse'?",                          o:["Dark red","Yellow-green","Sky blue","Deep purple"],a:"Yellow-green" },
      { q:"🎨 In printing (CMYK), what does K stand for?",            o:["Kyan","Khaki","Key (Black)","Kraft"],a:"Key (Black)" },
      { q:"🎨 What colour is indigo closest to?",                     o:["Red-orange","Blue-purple","Yellow-green","Pink"],a:"Blue-purple" },
      { q:"🎨 What colour symbolises danger/stop?",                   o:["Blue","Green","Yellow","Red"],a:"Red" },
    ],
    hard: [
      { q:"🎨 In light, red+green+blue at full intensity = ?",        o:["Brown","Black","White","Grey"],a:"White" },
      { q:"🎨 What is the wavelength range of visible red light?",    o:["380–450 nm","450–495 nm","570–590 nm","620–750 nm"],a:"620–750 nm" },
      { q:"🎨 HSL stands for?",                                       o:["Hue, Shadow, Light","Hue, Saturation, Lightness","High, Standard, Low","Heat, Shade, Level"],a:"Hue, Saturation, Lightness" },
      { q:"🎨 What colour does UV light appear to bees?",             o:["They can't see UV","Blue","Violet-white","Dark purple"],a:"Violet-white" },
      { q:"🎨 Hex #FF0000 represents?",                               o:["Green","Blue","Red","Yellow"],a:"Red" },
      { q:"🎨 What is 'tetrachromacy'?",                              o:["Seeing 2 primary colours","Seeing 4 types of colour receptors","Colour blindness","Seeing only grey"],a:"Seeing 4 types of colour receptors" },
      { q:"🎨 Hex #FFFFFF represents?",                               o:["Black","Grey","White","Transparent"],a:"White" },
      { q:"🎨 In Munsell colour system, what does 'chroma' mean?",    o:["Brightness","Colour purity/saturation","Hue angle","Value"],a:"Colour purity/saturation" },
      { q:"🎨 What colour is 'Rayleigh scattering' responsible for?", o:["Green sky","Red sky","Blue sky","Yellow sky"],a:"Blue sky" },
      { q:"🎨 In CMYK printing, mixing C+M gives?",                   o:["Red","Blue","Yellow","Purple"],a:"Blue" },
      { q:"🎨 Hex #000000 represents?",                               o:["White","Red","Black","Blue"],a:"Black" },
      { q:"🎨 Pantone is a system for?",                              o:["Standardising colours","Mixing paints","Digital screens","Photography"],a:"Standardising colours" },
      { q:"🎨 Which has the highest frequency in visible light?",     o:["Red","Orange","Yellow","Violet"],a:"Violet" },
      { q:"🎨 What does 'achromatic' mean in colour theory?",         o:["Very bright colours","Colours with hue","Without colour (grey/black/white)","Complementary colours"],a:"Without colour (grey/black/white)" },
      { q:"🎨 In RGB: rgb(0, 255, 0) produces?",                      o:["Red","Green","Blue","Yellow"],a:"Green" },
    ],
  },

  /* ── 13. SHAPES 🔷 ───────────────────────────────────────────
     Style: geometry basics, sides, angles, properties            */
  shapes: {
    easy: [
      { q:"🔷 Which shape has 3 sides?",                              o:["Circle","Square","Triangle","Rectangle"],a:"Triangle" },
      { q:"🔷 Circle vs Square — which has no corners?",              o:["Circle","Square","Both","Neither"],a:"Circle" },
      { q:"🔷 How many sides does a square have?",                    o:["3","4","5","6"],             a:"4" },
      { q:"🔷 Which shape is round?",                                 o:["Triangle","Square","Circle","Rectangle"],a:"Circle" },
      { q:"🔷 How many corners does a triangle have?",                o:["2","3","4","5"],             a:"3" },
      { q:"🔷 Which shape has 6 sides?",                              o:["Pentagon","Hexagon","Heptagon","Octagon"],a:"Hexagon" },
      { q:"🔷 A shape with 4 equal sides is a?",                      o:["Rectangle","Diamond","Square","Rhombus"],a:"Square" },
      { q:"🔷 How many sides does a pentagon have?",                  o:["4","5","6","7"],             a:"5" },
      { q:"🔷 Which shape looks like a ball?",                        o:["Cube","Sphere","Cone","Cylinder"],a:"Sphere" },
      { q:"🔷 Which shape has 8 sides?",                              o:["Hexagon","Heptagon","Octagon","Nonagon"],a:"Octagon" },
      { q:"🔷 A square is a special type of?",                        o:["Circle","Triangle","Rectangle","Pentagon"],a:"Rectangle" },
      { q:"🔷 How many faces does a cube have?",                      o:["4","5","6","8"],             a:"6" },
      { q:"🔷 Which shape is like an ice cream cone?",               o:["Cube","Sphere","Cone","Cylinder"],a:"Cone" },
      { q:"🔷 Which has the most sides: hexagon, octagon, pentagon?", o:["Hexagon","Octagon","Pentagon","All same"],a:"Octagon" },
      { q:"🔷 A rectangle has how many right angles?",                o:["2","3","4","5"],             a:"4" },
    ],
    medium: [
      { q:"🔷 What is the sum of angles in a triangle?",              o:["90°","120°","180°","270°"],  a:"180°" },
      { q:"🔷 Area of a square with side 7 cm = ?",                   o:["28 cm²","42 cm²","49 cm²","56 cm²"],a:"49 cm²" },
      { q:"🔷 Which quadrilateral has only one pair of parallel sides?",o:["Rectangle","Rhombus","Trapezoid","Parallelogram"],a:"Trapezoid" },
      { q:"🔷 Circumference of circle with diameter 14 cm (π≈3.14)?",o:["43.96 cm","44.96 cm","45.96 cm","46.96 cm"],a:"43.96 cm" },
      { q:"🔷 What is the sum of angles in a quadrilateral?",         o:["270°","360°","450°","540°"],a:"360°" },
      { q:"🔷 A rhombus has how many equal sides?",                   o:["1","2","3","4"],             a:"4" },
      { q:"🔷 Area of triangle with base 10 cm, height 6 cm?",        o:["25 cm²","30 cm²","35 cm²","60 cm²"],a:"30 cm²" },
      { q:"🔷 How many diagonals does a hexagon have?",               o:["6","7","8","9"],             a:"9" },
      { q:"🔷 Which 3D shape has 1 curved face and 2 flat faces?",    o:["Cube","Cone","Sphere","Cylinder"],a:"Cylinder" },
      { q:"🔷 Perimeter of rectangle: length 8 cm, width 5 cm?",      o:["24 cm","26 cm","28 cm","30 cm"],a:"26 cm" },
      { q:"🔷 A parallelogram's opposite angles are?",                o:["Supplementary","Equal","Complementary","Right angles"],a:"Equal" },
      { q:"🔷 Which polygon has interior angles summing to 540°?",    o:["Quadrilateral","Pentagon","Hexagon","Heptagon"],a:"Pentagon" },
      { q:"🔷 Volume of cube with edge 5 cm = ?",                     o:["75 cm³","100 cm³","125 cm³","150 cm³"],a:"125 cm³" },
      { q:"🔷 A regular hexagon can be divided into how many equilateral triangles?",o:["4","5","6","8"],a:"6" },
      { q:"🔷 Number of edges on a triangular prism?",                o:["6","7","8","9"],             a:"9" },
    ],
    hard: [
      { q:"🔷 Interior angle of a regular pentagon?",                 o:["100°","108°","110°","120°"],a:"108°" },
      { q:"🔷 Area of circle with radius 7 cm (π≈3.14)?",            o:["143.07 cm²","151.02 cm²","153.86 cm²","154.94 cm²"],a:"153.86 cm²" },
      { q:"🔷 How many faces does an icosahedron have?",              o:["12","16","20","24"],         a:"20" },
      { q:"🔷 Euler's formula for polyhedra: V − E + F = ?",          o:["0","1","2","3"],             a:"2" },
      { q:"🔷 Sum of exterior angles of any convex polygon = ?",      o:["180°","270°","360°","540°"],a:"360°" },
      { q:"🔷 A sphere has how many faces, edges, and vertices?",     o:["1,0,0","0,0,0","1,1,1","2,0,0"],a:"1,0,0" },
      { q:"🔷 Volume of sphere with radius 3 cm (V=4/3πr³, π≈3.14)?",o:["100.53 cm³","108.22 cm³","113.04 cm³","121.6 cm³"],a:"113.04 cm³" },
      { q:"🔷 How many diagonals in a decagon (10 sides)?",           o:["25","30","35","40"],         a:"35" },
      { q:"🔷 Interior angle sum of a nonagon (9 sides) = ?",         o:["1080°","1120°","1260°","1440°"],a:"1260°" },
      { q:"🔷 Which has more area: equilateral triangle or square with same perimeter?",o:["Triangle","Square","Both equal","Depends"],a:"Square" },
      { q:"🔷 A Koch snowflake has what type of perimeter?",          o:["Finite","Zero","Infinite","Changes"],a:"Infinite" },
      { q:"🔷 How many regular polyhedra (Platonic solids) exist?",   o:["3","4","5","6"],             a:"5" },
      { q:"🔷 The golden ratio φ ≈ ?",                                o:["1.414","1.618","1.732","2.236"],a:"1.618" },
      { q:"🔷 In a regular octagon, each interior angle = ?",         o:["120°","125°","130°","135°"],a:"135°" },
      { q:"🔷 Surface area of a cylinder: r=4, h=10 (SA=2πr(r+h))?",o:["351.68 cm²","351.86 cm²","352.68 cm²","353.68 cm²"],a:"351.68 cm²" },
    ],
  },

  /* ── 14. TRICK 🎩 ────────────────────────────────────────────
     Style: lateral thinking, twists, common misconceptions        */
  trick: {
    easy: [
      { q:"🎩 1 kg cotton vs 1 kg iron — which is heavier?",         o:["Cotton","Iron","Both same","Depends"],a:"Both same" },
      { q:"🎩 2 cats catch 2 mice in 2 minutes. How long for 1 cat to catch 1 mouse?",o:["1 min","2 min","4 min","30 sec"],a:"2 min" },
      { q:"🎩 How many months have 28 days?",                         o:["1","2","4","12"],            a:"12" },
      { q:"🎩 A rooster lays an egg on top of a roof. Which side does it roll?",o:["Left","Right","It doesn't — roosters don't lay eggs","Depends on wind"],a:"It doesn't — roosters don't lay eggs" },
      { q:"🎩 You have 3 apples and take away 2. How many do YOU have?",o:["1","2","3","0"],           a:"2" },
      { q:"🎩 What is the next letter: J, F, M, A, M, J, J, A, ?",   o:["S","O","N","D"],             a:"S" },
      { q:"🎩 How far can a dog run into a forest?",                   o:["1 km","5 km","Halfway","All the way"],a:"Halfway" },
      { q:"🎩 Which weighs more: a ton of gold or a ton of feathers?",o:["Gold","Feathers","Both same","Depends"],a:"Both same" },
      { q:"🎩 If you are in a race and overtake the person in 2nd — what position are you now?",o:["1st","2nd","3rd","4th"],a:"2nd" },
      { q:"🎩 What has hands but cannot clap?",                       o:["Robot","Clock","Glove","Puppet"],a:"Clock" },
      { q:"🎩 I speak without a mouth. What am I?",                   o:["Radio","Echo","Ghost","Phone"],a:"Echo" },
      { q:"🎩 A farmer has 17 sheep. All but 9 die. How many are left?",o:["8","9","10","17"],         a:"9" },
      { q:"🎩 What gets wetter the more it dries?",                   o:["Sponge","Rain","Towel","Ice"],a:"Towel" },
      { q:"🎩 Paul's parents have 3 sons: Snap, Crackle, and ?",      o:["Pop","Rock","Fizz","Paul"],  a:"Paul" },
      { q:"🎩 I have cities but no houses. What am I?",               o:["Globe","Map","Dream","Sky"],a:"Map" },
    ],
    medium: [
      { q:"🎩 If 5 workers take 5 days to build a wall, how long for 1 worker?",o:["1 day","5 days","10 days","25 days"],a:"25 days" },
      { q:"🎩 A snail is at bottom of a 10m well. Climbs 3m/day, slides 2m/night. Days to escape?",o:["8","9","10","11"],a:"8" },
      { q:"🎩 You light a candle, oil lamp, or fireplace. What do you light first?",o:["Candle","Lamp","Fireplace","A match"],a:"A match" },
      { q:"🎩 How many squares on a chessboard?",                     o:["64","100","204","Exactly 64"],a:"204" },
      { q:"🎩 A brick weighs 1 kg + half a brick. How much does a brick weigh?",o:["1 kg","1.5 kg","2 kg","2.5 kg"],a:"2 kg" },
      { q:"🎩 What occurs once in a minute, twice in a moment, never in 1000 years?",o:["A thought","The letter M","A second","A heartbeat"],a:"The letter M" },
      { q:"🎩 Move one matchstick: 6+4=4 becomes true. How?",        o:["6-4=2","6+4=10 (wrong)","6÷4≠4","8-4=4"],a:"8-4=4" },
      { q:"🎩 A plane crashes on the border of France and Spain. Where are survivors buried?",o:["France","Spain","Both countries","Survivors aren't buried"],a:"Survivors aren't buried" },
      { q:"🎩 Three doctors say Tom is their brother. Tom says he has no brothers. Who's lying?",o:["Tom","The doctors","All of them","Nobody — doctors are his sisters"],a:"Nobody — doctors are his sisters" },
      { q:"🎩 If all Bloops are Razzies but NOT all Razzies are Bloops — can a Razzies not be a Bloop?",o:["No","Yes","Sometimes","Cannot say"],a:"Yes" },
      { q:"🎩 You drive a bus. 10 get on, 3 off, 5 on, 2 off. What is the bus driver's eye colour?",o:["Brown","Blue","Unknown","Green"],a:"Unknown" },
      { q:"🎩 A man walks 1 km south, 1 km east, 1 km north — back to start. Where is he?",o:["Anywhere","North Pole","South Pole","Equator"],a:"North Pole" },
      { q:"🎩 What is the next in: 1, 11, 21, 1211, 111221, ?",      o:["312211","222111","121311","211231"],a:"312211" },
      { q:"🎩 How many birthdays does an average person have?",        o:["1","12","52","365"],          a:"1" },
      { q:"🎩 What has 4 legs in the morning, 2 at noon, 3 in evening?",o:["Clock","Cat","A human","Dog"],a:"A human" },
    ],
    hard: [
      { q:"🎩 Monty Hall: 3 doors, 1 car, 2 goats. You pick door 1. Host opens door 3 (goat). Switch?",o:["Stay with door 1","Switch to door 2","Doesn't matter","Always stay"],a:"Switch to door 2" },
      { q:"🎩 Two envelopes: one has 2× the other. You open yours: $100. Switch?",                   o:["Always switch","Never switch","It doesn't matter","Switch only if envelope feels heavy"],a:"It doesn't matter" },
      { q:"🎩 The liar/truth-teller puzzle: ask one question to find the correct path. Best question?",o:["Are you a liar?","What would the other say?","Which way is true?","Do you always lie?"],a:"What would the other say?" },
      { q:"🎩 A crocodile steals a child, promises to return if father guesses correctly. Father says 'You will NOT return.' What must the crocodile do?",o:["Return the child","Keep the child","Either","This is a paradox"],a:"This is a paradox" },
      { q:"🎩 This sentence is false. Is it true or false?",           o:["True","False","Both","Neither — it's a paradox"],a:"Neither — it's a paradox" },
      { q:"🎩 In the Prisoner's Dilemma, what is the Nash Equilibrium?",o:["Both cooperate","Both defect","One cooperates, one defects","Flip a coin"],a:"Both defect" },
      { q:"🎩 Zeno's paradox: can Achilles catch the tortoise?",      o:["No — infinite steps","Yes — infinite series converges","Only at infinity","No — depends on speed"],a:"Yes — infinite series converges" },
      { q:"🎩 Russell's Paradox: does the set of all sets that don't contain themselves contain itself?",o:["Yes","No","Both yes and no","This is a paradox"],a:"This is a paradox" },
      { q:"🎩 How many times does the digit 9 appear from 1–100?",     o:["9","10","11","20"],          a:"20" },
      { q:"🎩 Birthday paradox: how many people for 50%+ chance two share a birthday?",o:["183","100","50","23"],a:"23" },
      { q:"🎩 If you fold a paper 42 times (theoretically), thickness vs Moon?",o:["Thinner","Same","Reaches the Moon","Thicker than Moon-Earth distance"],a:"Reaches the Moon" },
      { q:"🎩 The unexpected hanging paradox: judge says 'hanged next week, day unknown'. Can the prisoner be surprised?",o:["No","Yes","Only on Friday","This is a paradox"],a:"This is a paradox" },
      { q:"🎩 In a room of 23 people, P(2 share birthday) > 50%. If room has 57 people, P > ?",o:["90%","95%","99%","50%"],a:"99%" },
      { q:"🎩 Hilbert's Hotel is full (∞ rooms). Can you fit one more guest?",o:["No","Yes","Only if a room is vacated","Infinity is finite"],a:"Yes" },
      { q:"🎩 Two trains 100 km apart approach each other at 50 km/h each. Bird flies 75 km/h between them till crash. Bird's total distance?",o:["75 km","100 km","125 km","150 km"],a:"75 km" },
    ],
  },

  /* ── 15. EMOTIONAL ❤️ ────────────────────────────────────────
     Style: behaviour, empathy, social situations                  */
  emotional: {
    easy: [
      { q:"❤️ Friend is sad. What should you do?",                    o:["Ignore them","Laugh at them","Comfort them","Walk away"],a:"Comfort them" },
      { q:"❤️ You see someone fall. You should?",                     o:["Laugh","Walk past","Help them up","Record a video"],a:"Help them up" },
      { q:"❤️ Friend shares toy with you. You say?",                  o:["Give it back immediately","Thank you!","It's mine now","Nothing"],a:"Thank you!" },
      { q:"❤️ You broke a vase. What is the right thing to do?",      o:["Hide it","Blame someone else","Say sorry","Pretend it didn't happen"],a:"Say sorry" },
      { q:"❤️ Someone is being bullied. You should?",                  o:["Join the bullying","Ignore it","Help the victim/tell an adult","Cheer"],a:"Help the victim/tell an adult" },
      { q:"❤️ You feel angry. The healthy thing to do is?",           o:["Hit something","Take deep breaths","Shout at others","Run away"],a:"Take deep breaths" },
      { q:"❤️ A new student joins your class. You should?",           o:["Ignore them","Make fun of them","Welcome them","Wait for them to approach you"],a:"Welcome them" },
      { q:"❤️ You get a gift you don't like. You say?",               o:["This is awful","Throw it","Thank you! I love it","Demand a different one"],a:"Thank you! I love it" },
      { q:"❤️ Your friend is crying. Which face matches how they feel? 😊😢😡😴",o:["😊","😢","😡","😴"],a:"😢" },
      { q:"❤️ You accidentally hurt someone. You?",                   o:["Run away","Say sorry and check they're OK","Pretend it was on purpose","Laugh"],a:"Say sorry and check they're OK" },
      { q:"❤️ Someone shares their lunch with you. You feel?",        o:["Angry","Grateful","Jealous","Bored"],a:"Grateful" },
      { q:"❤️ You win a game. The kind thing is to?",                 o:["Boast loudly","Celebrate quietly and say 'good game'","Ignore the loser","Tell everyone you're the best"],a:"Celebrate quietly and say 'good game'" },
      { q:"❤️ Friend is scared of the dark. You should?",             o:["Make fun of them","Help them feel safe","Leave them alone","Turn off the light"],a:"Help them feel safe" },
      { q:"❤️ Someone makes a mistake. Kind response is?",            o:["Laugh loudly","Point and stare","Encourage them to try again","Tell everyone"],a:"Encourage them to try again" },
      { q:"❤️ You're very happy. Which emoji matches? 😭🤩😡😴",      o:["😭","🤩","😡","😴"],    a:"🤩" },
    ],
    medium: [
      { q:"❤️ Friend is nervous before a test. Best advice?",         o:["Give up","Tests are useless","You'll do great! I believe in you","Who cares?"],a:"You'll do great! I believe in you" },
      { q:"❤️ Someone shares a secret with you. You?",                o:["Post it online","Tell everyone","Keep it safe","Forget it"],a:"Keep it safe" },
      { q:"❤️ Two friends argue. You are in the middle. You?",        o:["Take sides","Make it worse","Help them calm down","Walk away"],a:"Help them calm down" },
      { q:"❤️ Acting brave when scared is called?",                   o:["Lying","Rudeness","Courage","Silliness"],a:"Courage" },
      { q:"❤️ Worrying too much is called?",                          o:["Bravery","Excitement","Anxiety","Happiness"],a:"Anxiety" },
      { q:"❤️ Trying again after failing shows?",                     o:["Weakness","Fear","Giving up","Resilience"],a:"Resilience" },
      { q:"❤️ You feel overwhelmed. A helpful strategy?",             o:["Panic","Give up","Breathe and break it into steps","Ignore it"],a:"Breathe and break it into steps" },
      { q:"❤️ Doing something kind without being asked is?",          o:["Bossiness","Kindness","Shyness","Boredom"],a:"Kindness" },
      { q:"❤️ Someone posts something mean about you online. Best response?",o:["Reply meanly","Share it","Tell a trusted adult","Cry alone"],a:"Tell a trusted adult" },
      { q:"❤️ Which is the empathetic response to a sad friend?",     o:["Stop being sad","I understand how you feel","Just cheer up","Ignore them"],a:"I understand how you feel" },
      { q:"❤️ You disagree with a friend. Best way to handle it?",    o:["Shout","Gossip","Talk calmly about it","Ignore them forever"],a:"Talk calmly about it" },
      { q:"❤️ Accepting you are not perfect is called?",              o:["Arrogance","Weakness","Boasting","Self-compassion"],a:"Self-compassion" },
      { q:"❤️ Your best friend moves away. Healthy response?",        o:["Forget them","Get angry","Stay in touch and accept change","Stop caring"],a:"Stay in touch and accept change" },
      { q:"❤️ Which is NOT a way to manage stress?",                  o:["Exercise","Talk to someone","Bottle it up inside","Creative hobbies"],a:"Bottle it up inside" },
      { q:"❤️ Growth mindset means believing your abilities?",        o:["Cannot change","Are fixed at birth","Can improve with effort","Are unimportant"],a:"Can improve with effort" },
    ],
    hard: [
      { q:"❤️ Seeing things from another's point of view is?",        o:["Sympathy","Apathy","Jealousy","Empathy"],a:"Empathy" },
      { q:"❤️ Managing your own emotions is called?",                 o:["Self-pity","Self-regulation","Self-harm","Self-praise"],a:"Self-regulation" },
      { q:"❤️ Feeling happy when others suffer is called?",           o:["Empathy","Kindness","Grief","Schadenfreude"],a:"Schadenfreude" },
      { q:"❤️ 'I feel hurt when you say that' is an example of?",     o:["A threat","A lie","An accusation","An 'I' statement"],a:"An 'I' statement" },
      { q:"❤️ Unconsciously copying the emotions of others is?",      o:["Lying","Roleplay","Emotional contagion","Sympathy"],a:"Emotional contagion" },
      { q:"❤️ Assertive communication means?",                        o:["Shouting to get your way","Staying silent","Saying your needs clearly and respectfully","Only listening"],a:"Saying your needs clearly and respectfully" },
      { q:"❤️ Refusing to accept reality after a loss is?",           o:["Bargaining","Anger","Denial","Acceptance"],a:"Denial" },
      { q:"❤️ A friend lies to protect your feelings. This is a?",    o:["Big lie","True lie","White lie","No lie"],a:"White lie" },
      { q:"❤️ The ability to delay reward for bigger future gain is?",o:["Greed","Impatience","Fear","Impulse control"],a:"Impulse control" },
      { q:"❤️ Which is NOT a stage of grief (Kübler-Ross)?",          o:["Denial","Anger","Euphoria","Acceptance"],a:"Euphoria" },
      { q:"❤️ Cognitive dissonance occurs when?",                     o:["You are very happy","Your beliefs conflict with your actions","You forget something","You make a decision easily"],a:"Your beliefs conflict with your actions" },
      { q:"❤️ Which theory explains why we help strangers?",          o:["Selfish gene theory","Altruism","Narcissism","Apathy"],a:"Altruism" },
      { q:"❤️ Diffusion of responsibility means?",                    o:["Everyone helps quickly","People less likely to help when others are present","A single hero emerges","Responsibility is shared fairly"],a:"People less likely to help when others are present" },
      { q:"❤️ What is 'emotional intelligence' (EQ)?",                o:["IQ in disguise","Ability to perceive, manage, and express emotions","A personality disorder","Being very emotional"],a:"Ability to perceive, manage, and express emotions" },
      { q:"❤️ Stoicism teaches that happiness comes from?",           o:["Wealth","Controlling external events","Virtue and self-control","Fame"],a:"Virtue and self-control" },
    ],
  },
};

/* ── Category metadata (icon, label, colours for UI) ─────────── */
const CATS = {
  math:       { icon:"🔢", label:"Math",       color:"#b86800", bg:"#fff8e8" },
  logic:      { icon:"🧩", label:"Logic",      color:"#6820cc", bg:"#f5eeff" },
  pattern:    { icon:"🔁", label:"Pattern",    color:"#0070cc", bg:"#eaf3ff" },
  story:      { icon:"📖", label:"Story",      color:"#1a8040", bg:"#eafbee" },
  visual:     { icon:"👁",  label:"Visual",     color:"#cc5500", bg:"#fff4ee" },
  memory:     { icon:"🧠", label:"Memory",     color:"#8a0070", bg:"#faeeff" },
  speed:      { icon:"⚡", label:"Speed",      color:"#cc8800", bg:"#fffbea" },
  comparison: { icon:"⚖️", label:"Compare",    color:"#006680", bg:"#e8f8ff" },
  sequence:   { icon:"📅", label:"Sequence",   color:"#2a7000", bg:"#f0ffea" },
  word:       { icon:"📝", label:"Word",       color:"#208060", bg:"#eafaf4" },
  animals:    { icon:"🐾", label:"Animals",    color:"#804000", bg:"#fff5ea" },
  colors:     { icon:"🎨", label:"Colours",    color:"#cc0044", bg:"#fff0f4" },
  shapes:     { icon:"🔷", label:"Shapes",     color:"#004499", bg:"#eef4ff" },
  trick:      { icon:"🎩", label:"Trick",      color:"#440088", bg:"#f5eeff" },
  emotional:  { icon:"❤️", label:"Feelings",   color:"#cc2020", bg:"#fff0f0" },
};

/* ── Category background themes (body gradient per category) ─── */
const CAT_BG = {
  math:       "linear-gradient(150deg,#fffbe8 0%,#fff0cc 100%)",
  logic:      "linear-gradient(150deg,#f0e8ff 0%,#e8f0ff 100%)",
  pattern:    "linear-gradient(150deg,#e8f3ff 0%,#f0e8ff 100%)",
  story:      "linear-gradient(150deg,#e8fff0 0%,#f0ffe8 100%)",
  visual:     "linear-gradient(150deg,#fff0e8 0%,#fff8e0 100%)",
  memory:     "linear-gradient(150deg,#fae8ff 0%,#ffe8f5 100%)",
  speed:      "linear-gradient(150deg,#fffce0 0%,#fff0cc 100%)",
  comparison: "linear-gradient(150deg,#e0f8ff 0%,#e8fff8 100%)",
  sequence:   "linear-gradient(150deg,#eeffec 0%,#e8fff0 100%)",
  word:       "linear-gradient(150deg,#e8fff5 0%,#f0fff8 100%)",
  animals:    "linear-gradient(150deg,#fff5e0 0%,#fff8ea 100%)",
  colors:     "linear-gradient(150deg,#fff0f5 0%,#ffe8f0 100%)",
  shapes:     "linear-gradient(150deg,#eef0ff 0%,#e8f0ff 100%)",
  trick:      "linear-gradient(150deg,#f0e8ff 0%,#ffe8ff 100%)",
  emotional:  "linear-gradient(150deg,#fff0f0 0%,#ffe8ea 100%)",
};
